"""Row mapping for the FIFA2026 sheet: group fixtures (rows 4-75) and
knockout score-entry cell layout. Extracted from the template structure."""

# (row, group, home, away) — order as laid out in the sheet
GROUP_FIXTURES = [
    (4,  "A", "Mexico", "South Africa"),
    (5,  "A", "South Korea", "Czechia"),
    (6,  "A", "Czechia", "South Africa"),
    (7,  "A", "Mexico", "South Korea"),
    (8,  "A", "Czechia", "Mexico"),
    (9,  "A", "South Africa", "South Korea"),
    (10, "B", "Canada", "Bosnia and Herzegovina"),
    (11, "B", "Qatar", "Switzerland"),
    (12, "B", "Switzerland", "Bosnia and Herzegovina"),
    (13, "B", "Canada", "Qatar"),
    (14, "B", "Switzerland", "Canada"),
    (15, "B", "Bosnia and Herzegovina", "Qatar"),
    (16, "C", "Brazil", "Morocco"),
    (17, "C", "Haiti", "Scotland"),
    (18, "C", "Scotland", "Morocco"),
    (19, "C", "Brazil", "Haiti"),
    (20, "C", "Scotland", "Brazil"),
    (21, "C", "Morocco", "Haiti"),
    (22, "D", "United States", "Paraguay"),
    (23, "D", "Australia", "Turkey"),
    (24, "D", "Turkey", "Paraguay"),
    (25, "D", "United States", "Australia"),
    (26, "D", "Turkey", "United States"),
    (27, "D", "Paraguay", "Australia"),
    (28, "E", "Germany", "Curaçao"),
    (29, "E", "Ivory Coast", "Ecuador"),
    (30, "E", "Ecuador", "Curaçao"),
    (31, "E", "Germany", "Ivory Coast"),
    (32, "E", "Ecuador", "Germany"),
    (33, "E", "Curaçao", "Ivory Coast"),
    (34, "F", "Netherlands", "Japan"),
    (35, "F", "Sweden", "Tunisia"),
    (36, "F", "Tunisia", "Japan"),
    (37, "F", "Netherlands", "Sweden"),
    (38, "F", "Tunisia", "Netherlands"),
    (39, "F", "Japan", "Sweden"),
    (40, "G", "Belgium", "Egypt"),
    (41, "G", "Iran", "New Zealand"),
    (42, "G", "New Zealand", "Egypt"),
    (43, "G", "Belgium", "Iran"),
    (44, "G", "New Zealand", "Belgium"),
    (45, "G", "Egypt", "Iran"),
    (46, "H", "Spain", "Cape Verde"),
    (47, "H", "Saudi Arabia", "Uruguay"),
    (48, "H", "Uruguay", "Cape Verde"),
    (49, "H", "Spain", "Saudi Arabia"),
    (50, "H", "Uruguay", "Spain"),
    (51, "H", "Cape Verde", "Saudi Arabia"),
    (52, "I", "France", "Senegal"),
    (53, "I", "Iraq", "Norway"),
    (54, "I", "Norway", "Senegal"),
    (55, "I", "France", "Iraq"),
    (56, "I", "Norway", "France"),
    (57, "I", "Senegal", "Iraq"),
    (58, "J", "Argentina", "Algeria"),
    (59, "J", "Austria", "Jordan"),
    (60, "J", "Jordan", "Algeria"),
    (61, "J", "Argentina", "Austria"),
    (62, "J", "Algeria", "Austria"),
    (63, "J", "Jordan", "Argentina"),
    (64, "K", "Portugal", "Congo DR"),
    (65, "K", "Uzbekistan", "Colombia"),
    (66, "K", "Colombia", "Congo DR"),
    (67, "K", "Portugal", "Uzbekistan"),
    (68, "K", "Colombia", "Portugal"),
    (69, "K", "Congo DR", "Uzbekistan"),
    (70, "L", "England", "Croatia"),
    (71, "L", "Ghana", "Panama"),
    (72, "L", "Panama", "Croatia"),
    (73, "L", "England", "Ghana"),
    (74, "L", "Panama", "England"),
    (75, "L", "Croatia", "Ghana"),
]

# Knockout layout: per round -> (team_name_col, ft_col, otpk_col, row pairs)
# Team names appear in the *name* column once Excel recalculates.
KNOCKOUT = {
    "R32":   {"name": "BL", "ft": "BM", "otpk": "BN",
              "pairs": [(5, 6), (8, 9), (11, 12), (14, 15), (17, 18), (20, 21),
                        (23, 24), (26, 27), (29, 30), (32, 33), (35, 36),
                        (38, 39), (41, 42), (44, 45), (47, 48), (50, 51)]},
    "R16":   {"name": "BW", "ft": "BX", "otpk": "BY",
              "pairs": [(6, 7), (12, 13), (18, 19), (24, 25),
                        (30, 31), (36, 37), (42, 43), (48, 49)]},
    "QF":    {"name": "CH", "ft": "CI", "otpk": "CJ",
              "pairs": [(9, 10), (21, 22), (33, 34), (45, 46)]},
    "SF":    {"name": "CS", "ft": "CT", "otpk": "CU",
              "pairs": [(15, 16), (39, 40)]},
    "F3rd":  {"name": "DD", "ft": "DE", "otpk": "DF",
              "pairs": [(47, 48)]},   # 3rd-place playoff
    "Final": {"name": "DD", "ft": "DE", "otpk": "DF",
              "pairs": [(27, 28)]},
}

ALIASES = {
    "usa": "United States", "us": "United States", "united states of america": "United States",
    "bosnia": "Bosnia and Herzegovina", "bosnia-herzegovina": "Bosnia and Herzegovina",
    "bosnia & herzegovina": "Bosnia and Herzegovina",
    "curacao": "Curaçao",
    "dr congo": "Congo DR", "congo dr": "Congo DR", "democratic republic of the congo": "Congo DR",
    "czech republic": "Czechia",
    "turkiye": "Turkey", "türkiye": "Turkey",
    "south korea": "South Korea", "korea republic": "South Korea",
    "ivory coast": "Ivory Coast", "cote d'ivoire": "Ivory Coast", "côte d'ivoire": "Ivory Coast",
    "cabo verde": "Cape Verde",
}


def canon(name):
    n = name.strip()
    return ALIASES.get(n.lower(), n)
