"""Per-group dashboard content: star, what-to-watch fixture, biggest risk,
plus a 'group of death' difficulty score. Pairs with data/group_qual.json."""

# star = headline player; watch = the fixture that decides the group;
# risk = the most likely way Avraa's call breaks; tag = a fun one-word label.
DASH = {
 "A": {"tag": "Host opener", "star": "Hirving Lozano (MEX)",
       "watch": "South Korea vs Czechia (MD1) decides 2nd",
       "risk": "Czechia (68% qual) edges Korea for the runner-up spot",
       "fun": "Mexico opens the whole tournament at the Azteca, 2,240m up."},
 "B": {"tag": "Swiss lock", "star": "Granit Xhaka (SUI)",
       "watch": "Switzerland vs Canada (MD3) for top spot",
       "risk": "Co-host Canada (88% qual) wins the group outright",
       "fun": "Qatar (24% qual) is the field's weakest side — GD currency."},
 "C": {"tag": "Selecao march", "star": "Vinicius Jr (BRA)",
       "watch": "Scotland vs Morocco (MD2) for 2nd",
       "risk": "Scotland (69% qual) upsets Morocco for second",
       "fun": "Brazil at 98% qual even without Rodrygo and a doubtful Neymar."},
 "D": {"tag": "Coin-flip group", "star": "Arda Guler (TUR)",
       "watch": "Turkey vs USA (MD3) — 82% vs 81%, the tightest in the draw",
       "risk": "Turkey tops it and reroutes the whole bracket",
       "fun": "Genuinely the hardest group to call: three teams within 17 pp."},
 "E": {"tag": "German efficiency", "star": "Florian Wirtz (GER)",
       "watch": "Ecuador vs Germany (MD3) for the group",
       "risk": "Ecuador (88% qual, Elo 1935) wins the group, not just 2nd",
       "fun": "Germany vs Curacao is the tournament's biggest mismatch (92%)."},
 "F": {"tag": "Oranje cruise", "star": "Cody Gakpo (NED)",
       "watch": "Netherlands vs Japan (MD1) sets the tone",
       "risk": "Japan (76% qual) beats the Dutch and tops the group",
       "fun": "Both NED and JPN carry ACL/hamstring losses — depth decides."},
 "G": {"tag": "Soft draw", "star": "Kevin De Bruyne (BEL)",
       "watch": "Egypt vs Iran (MD3) for 2nd",
       "risk": "Iran (63% qual) edges Egypt behind Belgium",
       "fun": "Weakest group by rating — Belgium's easy path matters later."},
 "H": {"tag": "Champion runway", "star": "Lamine Yamal (ESP)",
       "watch": "Cape Verde vs Saudi Arabia — 35% vs 34% for the 3rd ticket",
       "risk": "Neither 3rd-placer qualifies; Uruguay slips to 2nd",
       "fun": "Spain at 99% qual; the only drama is the 3rd-place scrap."},
 "I": {"tag": "Haaland arrives", "star": "Erling Haaland (NOR)",
       "watch": "Norway vs Senegal (MD2) — the group's real final",
       "risk": "Senegal (82% qual) beats Norway and takes 2nd",
       "fun": "Norway's first World Cup since 1998, and Senegal is the field's best 3rd."},
 "J": {"tag": "Albiceleste glide", "star": "Lionel Messi (ARG)",
       "watch": "Algeria vs Austria (MD3) for 2nd",
       "risk": "Algeria (57% qual) overtakes Austria for the runner-up spot",
       "fun": "Argentina's lowest-variance group; Messi's last World Cup."},
 "K": {"tag": "Market rewrite", "star": "Cristiano Ronaldo (POR)",
       "watch": "Colombia vs Portugal (MD3) — the call that flipped on market data",
       "risk": "The Elo tie was right and Colombia (94% qual) tops the group",
       "fun": "Portugal & Colombia both above 94% qual — a two-horse group."},
 "L": {"tag": "Three Lions engine", "star": "Jude Bellingham (ENG)",
       "watch": "England vs Croatia (MD1), a knockout-quality opener",
       "risk": "Croatia (96% qual) wins the group instead of England",
       "fun": "England's reliability is what parks Croatia in its R32 slot."},
}
