"""Aggregate the documented Match Book entries into one live_stats object and
render it as LaTeX macros. This is the single source for every living number in
the paper, so no figure can drift out of sync. Pure."""
from match_book import FAILURE_MODES


def _exact(e):
    return list(e["pre"]["pick"]) == list(e["result"])


def compute(entries, latest_champion):
    n = len(entries)
    cum = sum(e["post"]["points"] for e in entries)
    mean_brier = sum(e["post"]["brier"] for e in entries) / n if n else 0.0
    exact = sum(1 for e in entries if _exact(e)) / n if n else 0.0
    tally = {k: 0 for k in FAILURE_MODES}
    for e in entries:
        if e["failure_mode"] in tally:
            tally[e["failure_mode"]] += 1
    champ_top = [[t, round(p, 4)] for t, p in
                 sorted(latest_champion.items(), key=lambda kv: -kv[1])[:5]]
    latest = max(entries, key=lambda e: e["match"]) if entries else None
    return {"documented": n, "cum_points": cum, "mean_brier": mean_brier,
            "exact_rate": exact, "re_ev_delta": 0, "champ_top": champ_top,
            "failure_tally": tally, "latest": latest}


def _version_line(s):
    """Title-page version line: each snapshot self-describes its state."""
    e = s.get("latest")
    if not e:
        return r"Pre-kickoff version, \today"
    scored = e["fixture"].replace(" v ", f" {e['result'][0]}--{e['result'][1]} ")
    iso = (e.get("kickoff") or e.get("documented_at") or "")[:10]
    if iso:
        from datetime import date
        d = date.fromisoformat(iso)
        return (f"Live edition --- after match {e['match']}, {scored} "
                f"({d.day} {d.strftime('%B')} {d.year})")
    return f"Live edition --- after match {e['match']}, {scored}"


def render_macros(s):
    lines = [
        "% GENERATED by scripts/live_stats.py — do not edit by hand.",
        r"\def\liveVersionLine{%s}" % _version_line(s),
        r"\def\liveDocumented{%d}" % s["documented"],
        r"\def\liveCumPoints{%d}" % s["cum_points"],
        r"\def\liveMeanBrier{%.2f}" % s["mean_brier"],
        r"\def\liveExactRate{%.2f}" % s["exact_rate"],
        r"\def\liveReEvDelta{%+d}" % s["re_ev_delta"],
    ]
    return "\n".join(lines) + "\n"
