"""Aggregate the documented Match Book entries into one live_stats object and
render it as LaTeX macros. This is the single source for every living number in
the paper, so no figure can drift out of sync. Pure."""
from match_book import FAILURE_MODES


def _exact(e):
    return list(e["pre"]["pick"]) == list(e["result"])


def compute(entries, latest_champion):
    n = len(entries)
    cum = sum(e["post"]["points"] for e in entries)
    mean_brier = sum(e["post"]["brier"] for e in entries) / n if n else 0.0
    exact = sum(1 for e in entries if _exact(e)) / n if n else 0.0
    tally = {k: 0 for k in FAILURE_MODES}
    for e in entries:
        if e["failure_mode"] in tally:
            tally[e["failure_mode"]] += 1
    champ_top = [[t, round(p, 4)] for t, p in
                 sorted(latest_champion.items(), key=lambda kv: -kv[1])[:5]]
    latest = max(entries, key=lambda e: e["match"]) if entries else None
    total_bits = sum(e["post"].get("info_bits", 0.0) for e in entries) if entries else 0.0
    bits_of_max = 100 * total_bits / 6.6 if total_bits > 0 else 0.0
    return {"documented": n, "cum_points": cum, "mean_brier": mean_brier,
            "exact_rate": exact, "re_ev_delta": 0, "champ_top": champ_top,
            "failure_tally": tally, "latest": latest,
            "total_bits": total_bits, "bits_of_max": bits_of_max}


def _version_line(s):
    """Title-page version line: each snapshot self-describes its state."""
    e = s.get("latest")
    if not e:
        return r"Pre-kickoff version, \today"
    fixture = e.get("fixture", f"match {e['match']}")
    scored = fixture.replace(" v ", f" {e['result'][0]}--{e['result'][1]} ")
    iso = (e.get("kickoff") or e.get("documented_at") or "")[:10]
    if iso:
        from datetime import date
        d = date.fromisoformat(iso)
        return (f"Live edition --- after match {e['match']}, {scored} "
                f"({d.day} {d.strftime('%B')} {d.year})")
    return f"Live edition --- after match {e['match']}, {scored}"


def _abstract_revision(s):
    """One generated sentence appended to the abstract/intro forecast claims:
    the same numbers, re-stated conditionally for this edition."""
    top = s.get("champ_now_top")
    if not top or not s["documented"]:
        return ""
    parts = ([f"{top[0][0]} at {100*top[0][1]:.1f} percent"]
             + [f"{t} at {100*p:.1f}" for t, p in top[1:3]])
    inner = ", ".join(parts[:-1]) + f", and {parts[-1]}"
    n = s["documented"]
    word = "result" if n == 1 else "results"
    return (f" Conditioned on the {n} {word} played so far, "
            f"this edition's forecast has {inner}.")


def _update_log(s):
    """Accumulated revision log appended to the title-page update-log footnote."""
    entries = s.get("entries") or []
    if not entries:
        return ""
    items = "; ".join(
        f"M{e['match']} " + e.get("fixture", "").replace(
            " v ", f" {e['result'][0]}--{e['result'][1]} ")
        for e in entries)
    return (f" Live revision log --- results conditioned into this edition: "
            f"{items}. All forecast tables, the abstract headline, and the "
            f"trajectory figure are re-stated on this information; the locked "
            f"pre-kickoff edition is preserved at tag prereg-2026.")


def render_macros(s):
    champ_b_top = s.get("champ_b_top") or []
    b_revision = ", ".join(
        f"{t} {100*p:.1f}\\%{{}}" for t, p in champ_b_top[:3]
    ) if champ_b_top else ""
    lines = [
        "% GENERATED by scripts/live_stats.py — do not edit by hand.",
        r"\def\liveVersionLine{%s}" % _version_line(s),
        r"\def\liveAbstractRevision{%s}" % _abstract_revision(s),
        r"\def\liveUpdateLog{%s}" % _update_log(s),
        r"\def\liveDocumented{%d}" % s["documented"],
        r"\def\liveCumPoints{%d}" % s["cum_points"],
        r"\def\liveMeanBrier{%.2f}" % s["mean_brier"],
        r"\def\liveExactRate{%.2f}" % s["exact_rate"],
        r"\def\liveRealVsEVDelta{%+d}" % s.get("real_vs_ev_delta", s.get("re_ev_delta", 0)),
        r"\def\liveEditionNum{%03d}" % (s["latest"]["match"] if s.get("latest") else 0),
        r"\def\liveTotalBits{%.2f}" % s.get("total_bits", 0.0),
        r"\def\liveBitsOfMax{%.1f}" % s.get("bits_of_max", 0.0),
        r"\def\liveTrackBRevision{%s}" % b_revision,
    ]
    return "\n".join(lines) + "\n"
