"""Aggregate the documented Match Book entries into one live_stats object and
render it as LaTeX macros. This is the single source for every living number in
the paper, so no figure can drift out of sync. Pure."""
from match_book import FAILURE_MODES


def _exact(e):
    return list(e["pre"]["pick"]) == list(e["result"])


def compute(entries, latest_champion):
    n = len(entries)
    cum = sum(e["post"]["points"] for e in entries)
    mean_brier = sum(e["post"]["brier"] for e in entries) / n if n else 0.0
    exact = sum(1 for e in entries if _exact(e)) / n if n else 0.0
    tally = {k: 0 for k in FAILURE_MODES}
    for e in entries:
        if e["failure_mode"] in tally:
            tally[e["failure_mode"]] += 1
    champ_top = [[t, round(p, 4)] for t, p in
                 sorted(latest_champion.items(), key=lambda kv: -kv[1])[:5]]
    return {"documented": n, "cum_points": cum, "mean_brier": mean_brier,
            "exact_rate": exact, "re_ev_delta": 0, "champ_top": champ_top,
            "failure_tally": tally}


def render_macros(s):
    lines = [
        "% GENERATED by scripts/live_stats.py — do not edit by hand.",
        r"\def\liveDocumented{%d}" % s["documented"],
        r"\def\liveCumPoints{%d}" % s["cum_points"],
        r"\def\liveMeanBrier{%.2f}" % s["mean_brier"],
        r"\def\liveExactRate{%.2f}" % s["exact_rate"],
        r"\def\liveReEvDelta{%+d}" % s["re_ev_delta"],
    ]
    return "\n".join(lines) + "\n"
