"""Render every living unit of the paper to its own generated file under
paper/live/. The skeleton WC2026_paper.tex carries only permanent \\input lines
and is never written by the pipeline; skeleton_hash + data/skeleton_sha256.txt
prove it byte-identical on every run. Pure renderers: context in, tex out."""
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import render_evolution as rev
import poisson_model as pm
import draft_sections as _ds

HEADER = "% GENERATED by scripts/render_live.py — do not edit by hand.\n"


def skeleton_hash(tex):
    return hashlib.sha256(tex.encode()).hexdigest()


def write_unit(live_dir, name, content):
    Path(live_dir).mkdir(parents=True, exist_ok=True)
    (Path(live_dir) / f"{name}.tex").write_text(HEADER + content + "\n",
                                                encoding="utf-8")


def validate_labels(name, content, required):
    """Raise ValueError if any required \\label{tag} is absent from content."""
    for label in required:
        if f"\\label{{{label}}}" not in content:
            raise ValueError(
                f"render_live: {name}.tex missing \\label{{{label}}} — "
                f"add it to the generator or the prompt template")


def outcome_probs(lh, la):
    """Normalized P(H/D/A) for display (poisson_model's raw triple loses the
    truncated mass beyond MAX_G goals)."""
    ph, pd, pa = pm.outcome_probs(lh, la)
    s = ph + pd + pa
    return ph / s, pd / s, pa / s


def _pct(x):
    return f"{100 * x:.1f}"


# Team -> flag markup, matching the locked group matrices in the skeleton:
# most teams use \worldflag (ISO-2), three use the preamble's custom TikZ flags.
_FLAG_ISO = {
    "Algeria": "DZ", "Argentina": "AR", "Australia": "AU", "Austria": "AT",
    "Belgium": "BE", "Bosnia and Herzegovina": "BA", "Brazil": "BR",
    "Canada": "CA", "Cape Verde": "CV", "Colombia": "CO", "Congo DR": "CD",
    "Croatia": "HR", "Czechia": "CZ", "Ecuador": "EC", "Egypt": "EG",
    "France": "FR", "Germany": "DE", "Ghana": "GH", "Haiti": "HT", "Iran": "IR",
    "Iraq": "IQ", "Ivory Coast": "CI", "Japan": "JP", "Jordan": "JO",
    "Mexico": "MX", "Morocco": "MA", "Netherlands": "NL", "New Zealand": "NZ",
    "Norway": "NO", "Panama": "PA", "Paraguay": "PY", "Portugal": "PT",
    "Qatar": "QA", "Saudi Arabia": "SA", "Senegal": "SN", "South Africa": "ZA",
    "South Korea": "KR", "Spain": "ES", "Sweden": "SE", "Switzerland": "CH",
    "Tunisia": "TN", "Turkey": "TR", "United States": "US", "Uruguay": "UY",
    "Uzbekistan": "UZ",
}
_FLAG_CUSTOM = {"England": "\\flagENG", "Scotland": "\\flagSCO", "Curaçao": "\\flagCUW"}

# Three-letter FIFA codes — compact, fixed-width team labels so every group
# table is the same width regardless of how long the team names are.
_CODE3 = {
    "Mexico": "MEX", "South Korea": "KOR", "Czechia": "CZE", "South Africa": "RSA",
    "Switzerland": "SUI", "Canada": "CAN", "Bosnia and Herzegovina": "BIH",
    "Qatar": "QAT", "Brazil": "BRA", "Morocco": "MAR", "Scotland": "SCO",
    "Haiti": "HAI", "United States": "USA", "Turkey": "TUR", "Paraguay": "PAR",
    "Australia": "AUS", "Germany": "GER", "Ecuador": "ECU", "Ivory Coast": "CIV",
    "Curaçao": "CUW", "Netherlands": "NED", "Japan": "JPN", "Sweden": "SWE",
    "Tunisia": "TUN", "Belgium": "BEL", "Egypt": "EGY", "Iran": "IRN",
    "New Zealand": "NZL", "Spain": "ESP", "Uruguay": "URU", "Cape Verde": "CPV",
    "Saudi Arabia": "KSA", "France": "FRA", "Norway": "NOR", "Senegal": "SEN",
    "Iraq": "IRQ", "Argentina": "ARG", "Austria": "AUT", "Algeria": "ALG",
    "Jordan": "JOR", "Portugal": "POR", "Colombia": "COL", "Uzbekistan": "UZB",
    "Congo DR": "COD", "England": "ENG", "Croatia": "CRO", "Panama": "PAN",
    "Ghana": "GHA",
}


def _code3(team):
    return _CODE3.get(team, team[:3].upper())


def _flag(team):
    """Mini flag for a team, sized to match the locked group matrices (4mm×2.7mm)."""
    if team in _FLAG_CUSTOM:
        return f"\\resizebox{{4mm}}{{2.7mm}}{{{_FLAG_CUSTOM[team]}[10mm]}}"
    iso = _FLAG_ISO.get(team)
    if iso:
        return f"\\resizebox{{4mm}}{{2.7mm}}{{\\worldflag[width=10mm]{{{iso}}}}}"
    return ""


# ---- ported units (reuse render_evolution's pure builders) ----

def ledger(entries, upcoming=None):
    return rev.ledger_table(entries, upcoming=upcoming)


def narrative_unit(entries):
    return rev.narrative(entries)


def trajfig_unit(entries, live_fig):
    return rev.trajfig(entries, live_fig)


def champ_table_unit(frozen, now, n_results, champion_b=None):
    return rev.champ_table(frozen, now, n_results, champion_b=champion_b)


def divergence_unit(frozen, now, entries, group_state, champion_b=None, now_b=None):
    played = [g for g in group_state if g["played"]]
    return rev.divergence_section(frozen, now, entries, played, champion_b=champion_b, now_b=now_b)


# ---- new units ----

def tracker(group_state, frozen, now):
    """Main-text 'state of the group stage': one row per group. frozen is
    accepted for signature symmetry with the other units; the table shows
    only current values."""
    rows = []
    for g in group_state:
        top2 = g["rows"][:2]
        if g["played"]:
            standing = "; ".join(f"{r['team']} {r['Pts']}" for r in top2)
        else:
            standing = "--"
        leaders = sorted((r for r in g["rows"] if r["team"] in now),
                         key=lambda r: -now[r["team"]]["advance_KO"])[:2]
        qual = "; ".join(
            f"{r['team']} {_pct(now[r['team']]['advance_KO'])}" for r in leaders)
        rows.append(f"{g['group']} & {g['played']}/{g['total']} & {standing} & {qual} \\\\")
    return (
        "\\begin{table}[!t]\n  \\centering\n"
        "  \\caption{State of the group stage (live edition)}\\label{tab:tracker}\n"
        "  \\begin{footnotesize}\n"
        "  {\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} clll}\n"
        "    \\toprule\n"
        "    Group & Played & Standings (top two, real points) & Advance now (top two) \\\\\n"
        "    \\midrule\n    " + "\n    ".join(rows) + "\n"
        "    \\bottomrule\n  \\end{tabular*}}\n  \\end{footnotesize}\n\\end{table}")


def _record_from(team, group_exps, res_by_match, resolver):
    """Tally (W, D, L, Pts) for `team` across its group fixtures, taking played
    matches from `res_by_match` and unplayed ones from resolver(e) -> (hg, ag)."""
    w = d = l = pts = 0
    for e in group_exps:
        if team not in (e["home"], e["away"]):
            continue
        res = res_by_match.get(str(e["match"]))
        hg, ag = (tuple(res) if res else resolver(e))
        tf, ta = (hg, ag) if e["home"] == team else (ag, hg)
        if tf > ta:
            w += 1; pts += 3
        elif tf == ta:
            d += 1; pts += 1
        else:
            l += 1
    return w, d, l, pts


def group_box(g_state, results, expectations, frozen, now, now_b=None, track_b=None):
    """Appendix-A unified group table (spec 3.15) — ONE table per group, in the
    locked-matrix style: flag column headers (no rotated names), flag+name row
    labels, and a round-robin body whose played cells carry the bold actual score
    + check/cross and whose upcoming cells carry the predicted scoreline under
    Frozen/Track~A (one line, since both ride the June-10 ratings) and Track~B.
    Right panels give the Actual record (W/D/L/Pts/Qual\\%) and the projected
    final W/D/L/Pts under Frozen/Track~A and under Track~B. A remaining-fixtures
    H/D/A block sits below. track_b: {match: {'pick':[h,a],'hda':[h,d,a]}}."""
    grp = g_state["group"]
    teams = [r["team"] for r in g_state["rows"]]
    group_exps = [e for e in expectations if e.get("group") == grp]
    exps = {(e["home"], e["away"]): e for e in group_exps}
    res_by_match = results["group"]
    track_b = track_b or {}

    if not group_exps:
        return f"\\paragraph{{Group {grp} — live.}} Fixtures pending."

    def _sgn(x): return 1 if x > 0 else (-1 if x < 0 else 0)

    def _frozen_pick(e):                # Frozen and Track A share the submitted pick
        return tuple(e["pick"])

    def _track_b_pick(e):
        return tuple(track_b.get(e["match"], {}).get("pick", e["pick"]))

    # ---- one round-robin table, locked-matrix style -------------------------
    n = len(teams)
    col_spec = "cl" + "c" * n + "cccc"
    flag_hdr = " & ".join(_flag(t) for t in teams)
    panel_hdr = (
        "\\makecell{Actual \\\\ W/D/L/P} & "
        "\\makecell{Frozen \\\\ W/D/L/P/Q\\%} & "
        "\\makecell{Track~A \\\\ W/D/L/P/Q\\%} & "
        "\\makecell{Track~B \\\\ W/D/L/P/Q\\%}")
    header = f" & Team & {flag_hdr} & {panel_hdr} \\\\"

    body_rows = []
    for rank, home in enumerate(teams, 1):
        cells = []
        for away in teams:
            if home == away:
                cells.append("---")
                continue
            e = exps.get((home, away)) or exps.get((away, home))
            if e is None:
                cells.append("?")
                continue
            res = res_by_match.get(str(e["match"]))
            if res:                      # played: bold actual score + correct mark
                score = (f"{res[0]}--{res[1]}" if e["home"] == home
                         else f"{res[1]}--{res[0]}")
                pick = e["pick"]
                correct = _sgn(pick[0] - pick[1]) == _sgn(res[0] - res[1])
                icon = r"$\checkmark$" if correct else r"$\times$"
                cells.append(f"\\textbf{{{score}}}{icon}")
            else:                        # upcoming: per-track scoreline + H/D/A,
                fa, tb = _frozen_pick(e), _track_b_pick(e)   # folding in the old fixtures block
                fhda = e["probs_HDA"]                        # Frozen = Track A (market-based)
                bhda = track_b.get(e["match"], {}).get("hda")
                if e["home"] == home:
                    f_s, b_s = f"{fa[0]}--{fa[1]}", f"{tb[0]}--{tb[1]}"
                    f_h, b_h = fhda, bhda
                else:
                    f_s, b_s = f"{fa[1]}--{fa[0]}", f"{tb[1]}--{tb[0]}"
                    f_h = [fhda[2], fhda[1], fhda[0]]
                    b_h = [bhda[2], bhda[1], bhda[0]] if bhda else None
                fh = "/".join(str(round(100 * x)) for x in f_h)
                bh = "/".join(str(round(100 * x)) for x in b_h) if b_h else "--"
                cells.append(
                    f"\\makecell{{F/A {f_s}\\,{fh} \\\\ B {b_s}\\,{bh}}}")

        # right panels — each W/D/L/Pts/Qual%: Actual (real record + current
        # qual), then projected final record under Frozen / Track A / Track B.
        # Records coincide for Frozen and Track A (shared June-10 ratings); the
        # qualification probabilities differ because Track A is result-conditioned.
        row = next((r for r in g_state["rows"] if r["team"] == home), {})
        aw, ad, al = row.get("W", 0), row.get("D", 0), row.get("L", 0)
        apts = row.get("Pts", 0)
        q_frozen = _pct(frozen[home]["advance_KO"]) if home in frozen else "--"
        q_a = _pct(now[home]["advance_KO"]) if home in now else "--"
        q_b = _pct(now_b[home]["advance_KO"]) if (now_b and home in now_b) else "--"
        actual = f"{aw}/{ad}/{al}/{apts}" if g_state["played"] else "--"
        fw, fd, fl, fp = _record_from(home, group_exps, res_by_match, _frozen_pick)
        bw, bd, bl, bp = _record_from(home, group_exps, res_by_match, _track_b_pick)
        body_rows.append(
            f"{rank} & {_flag(home)}~{_code3(home)} & " + " & ".join(cells)
            + f" & {actual} & {fw}/{fd}/{fl}/{fp}/{q_frozen}\\%"
            f" & {fw}/{fd}/{fl}/{fp}/{q_a}\\% & {bw}/{bd}/{bl}/{bp}/{q_b}\\% \\\\"
        )

    # ---- remaining-fixtures H/D/A block (below the matrix) -------------------
    state = (f"{g_state['played']} of {g_state['total']} played"
             if g_state["played"] else "fixtures pending")
    note = ("Teams are 3-letter codes. Round-robin body: row team's score against "
            "the column team. Played cells show the actual score in bold with "
            "$\\checkmark$/$\\times$ for the submitted result pick; upcoming cells "
            "give, per track, the predicted scoreline and the H/D/A outcome "
            "probabilities (\\%) --- line F/A is Frozen=Track~A, line B is Track~B. "
            "Right panels report W/D/L/Pts and qualification \\%: Actual is the real "
            "record so far; Frozen, Track~A, and Track~B give the projected final "
            "record (each remaining game resolved at that track's predicted "
            "scoreline) and that track's qual. Frozen and Track~A share the June~10 "
            "ratings, so their scoreline, H/D/A, and projected record coincide; the "
            "two diverge only in the conditioned qualification \\%.")

    return (
        f"\\paragraph{{Group {grp} — live ({state}).}}\\leavevmode\\par\n"
        "\\noindent\\begin{threeparttable}\n"
        "{\\setlength{\\tabcolsep}{2pt}\\tiny\n"
        f"\\begin{{tabular*}}{{\\textwidth}}{{@{{\\extracolsep{{\\fill}}}}{col_spec}@{{}}}}\n"
        "\\toprule\n"
        f"{header}\n"
        "\\midrule\n"
        + "\n".join(body_rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular*}}\n"
        "\\begin{tablenotes}\\notesize\n"
        f"\\item \\textit{{Notes}}: {note}\n"
        "\\end{tablenotes}\n\\end{threeparttable}\n"
    )


def two_track_unit(two_track, learning, fig, info_snapshot=None, track_a=None,
                   champion_b=None, frozen_stages=None):
    """The live A-vs-B: Frozen / Track A / Track B champion odds and Elo drift.
    track_a: dict of {team: {champion: prob, ...}} (Track A / now_probs).
    champion_b: dict of {team: prob} from champion_b post record (preferred Track B source).
    frozen_stages: dict of {team: {champion: prob, ...}} from frozen_stage_probs (preferred Frozen source).
    info_snapshot: no longer used here (provenance moved to data_revealed)."""
    if two_track is None:
        return ("\\textit{Two-track live results begin with the first match "
                "whose box score is collected.}")
    # Use frozen_stages (200k-sim baseline) when available; fall back to two_track['frozen']
    frozen_src = {t: d["champion"] for t, d in frozen_stages.items()} if frozen_stages else two_track["frozen"]
    teams = sorted(frozen_src, key=lambda t: -frozen_src.get(t, 0.0))[:8]
    if track_a is not None:
        # Track B: prefer champion_b (consistent with Table 3); fall back to two_track['learning']
        b_src = champion_b if champion_b else two_track["learning"]
        rows = "\n".join(
            f"{t} & {_pct(frozen_src.get(t, 0.0))} & "
            f"{_pct(track_a.get(t, {}).get('champion', 0.0))} & "
            f"{_pct(b_src.get(t, 0.0))} & "
            f"{100*(track_a.get(t, {}).get('champion', 0.0) - frozen_src.get(t, 0.0)):+.1f} \\\\"
            for t in teams)
        header = ("Team & Frozen (\\%) & Track~A (\\%) & Track~B (\\%) & "
                  "$\\Delta$ (A$-$Frozen, pp) \\\\\n\\midrule\n")
        col_spec = "lrrrr"
    else:
        b_src = champion_b if champion_b else two_track["learning"]
        rows = "\n".join(
            f"{t} & {_pct(frozen_src.get(t, 0.0))} & "
            f"{_pct(b_src.get(t, 0.0))} & "
            f"{100*(b_src.get(t, 0.0) - frozen_src.get(t, 0.0)):+.1f} \\\\"
            for t in teams)
        header = "Team & Frozen (\\%) & Track~B (\\%) & $\\Delta$ (pp) \\\\\n\\midrule\n"
        col_spec = "lrrr"
    drifts = sorted(learning["drift"].items(), key=lambda kv: -abs(kv[1]))[:8]
    drift_rows = "\n".join(f"{t} & {d:+.1f} \\\\" for t, d in drifts)
    pend = (f" Stats pending for matches: "
            f"{', '.join(f'M{m:03d}' for m in learning['pending'])}."
            if learning["pending"] else "")
    fig_block = ("\\begin{figure}[!t]\n  \\caption{Two tracks live: Frozen vs "
                 "Track~A vs Track~B champion paths}\\label{fig:twotracklive}\n"
                 "  {\\centering\\includegraphics[width=0.94\\textwidth]"
                 "{figs/fig_two_track_live.pdf}\\par}\n\\end{figure}\n" if fig else "")
    n = len(learning["processed"])

    return (
        "\\subsection{The two tracks live: 2026 as it speaks}"
          "\\label{sec:twotracklive}\n"
          f"The pre-registered A-vs-B study of Appendix~D, running on the real "
          f"tournament: after each match the observed shot performance "
          f"($\\lambda_{{\\mathrm{{obs}}}}$, Appendix~D.2) updates Track~B's "
          f"ratings (k=50, locked), while Track~A re-conditions "
          f"on results alone. {n} match(es) processed so far.{pend}\n\n"
        + fig_block
        + "\\begin{footnotesize}\n"
          f"\\begin{{tabular}}{{{col_spec}}}\n\\toprule\n"
        + header
        + rows
        + "\n\\bottomrule\n\\end{tabular}\\qquad\n"
          "\\begin{tabular}{lr}\n\\toprule\nTeam & Drift (Elo) \\\\\n\\midrule\n"
        + drift_rows
        + "\n\\bottomrule\n\\end{tabular}\n\\end{footnotesize}"
    )


def _stats_release(match, match_stats, learning):
    s = match_stats.get(match)
    rec = next((r for r in learning["processed"] if r["match"] == match), None)
    if s is None:
        return ("\\textit{Box-score statistics for this match are pending; the "
                "performance analysis will appear in the next edition.}")
    def _row(label, key, fmt="{:.0f}"):
        return (f"{label} & " + fmt.format(s['home'][key]) + " & "
                + fmt.format(s['away'][key]) + " \\\\")
    lines = [_row("Shots", "total_shots"), _row("On target", "sot")]
    if (s["home"].get("possession") is not None
            and s["away"].get("possession") is not None):
        lines.append(_row("Possession (\\%)", "possession", "{:.0f}"))
    perf = ""
    if rec:
        perf = (f"\\\\[2pt] Performance vs.\\ expectation: "
                f"$\\lambda_{{\\mathrm{{obs}}}}$ = {rec['lam_obs']['home']:.2f} / "
                f"{rec['lam_obs']['away']:.2f} against "
                f"$\\lambda_{{\\mathrm{{exp}}}}$ = {rec['lam_exp']['home']:.2f} / "
                f"{rec['lam_exp']['away']:.2f} "
                f"({rec['lam_obs']['source']} signal); the learning track moves "
                f"{rec['home']} by {rec['drift_after'].get(rec['home'], 0):+.1f} and "
                f"{rec['away']} by {rec['drift_after'].get(rec['away'], 0):+.1f} Elo.")
    return ("\\begin{table}[!h]\\centering\n"
            "\\caption{Match statistics (live edition M\\liveEditionNum{})}\\label{tab:live_edition_snapshot}\n"
            "\\begin{footnotesize}\\begin{tabular}{lrr}\\toprule\n"
            f" & {s['home']['team']} & {s['away']['team']} \\\\\n\\midrule\n"
            + "\n".join(lines) + "\n\\bottomrule\\end{tabular}\\end{footnotesize}"
            + perf
            + "\n\\end{table}")


def _cumulative_stats_table(entries, match_stats, expectations):
    """Table 7: one row per played match, grows with each edition.
    Columns: Game | Shots H–A | On target H–A | Poss H–A | Frozen H/D/A | Track B H/D/A.
    Track B H/D/A is stored in entry['pre']['probs_HDA_b'] at documentation time
    (pre-match learn_ratings); '--' for entries documented before this feature."""
    rows = []
    exp_by_match = {e["match"]: e for e in expectations}
    has_b = any(e.get("pre", {}).get("probs_HDA_b") for e in entries)
    for e in sorted(entries, key=lambda x: x["match"]):
        m = e["match"]
        s = match_stats.get(m)
        if s is None:
            continue
        sh = s["home"].get("total_shots", "--")
        sa = s["away"].get("total_shots", "--")
        oh = s["home"].get("sot", "--")
        oa = s["away"].get("sot", "--")
        ph = s["home"].get("possession")
        pa = s["away"].get("possession")
        poss = f"{ph:.0f}--{pa:.0f}" if ph is not None and pa is not None else "--"
        exp = exp_by_match.get(m)
        hda = "/".join(_pct(p) for p in exp["probs_HDA"]) if exp else "--"
        hda_b_raw = e.get("pre", {}).get("probs_HDA_b")
        hda_b = "/".join(_pct(p) for p in hda_b_raw) if hda_b_raw else "--"
        if has_b:
            rows.append(
                f"M{m} {e['fixture']} & {sh}--{sa} & {oh}--{oa} & {poss} & {hda} & {hda_b} \\\\"
            )
        else:
            rows.append(
                f"M{m} {e['fixture']} & {sh}--{sa} & {oh}--{oa} & {poss} & {hda} \\\\"
            )
    if not rows:
        return r"\textit{Match statistics pending.}"
    if has_b:
        col_spec = "lccccc"
        header = ("Game & Shots (H--A) & On target (H--A) & Poss\\% (H--A) & "
                  "Frozen H/D/A & Track~B H/D/A \\\\\n")
    else:
        col_spec = "lcccc"
        header = "Game & Shots (H--A) & On target (H--A) & Poss\\% (H--A) & Frozen H/D/A \\\\\n"
    return (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Cumulative match statistics (live edition "
        "M\\liveEditionNum{})}\\label{tab:live_match_stats}\n"
        f"\\begin{{footnotesize}}\\begin{{tabular}}{{{col_spec}}}\\toprule\n"
        + header
        + "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\\end{footnotesize}\n\\end{table}"
    )


def revision_report(ctx):
    """The central-bank release: data release, forecast revision vs the
    previous edition, implications, vintages. Driver contract: ctx
    vintages_rows already contains THIS edition's row (so [-2] is the
    previous edition) and ctx['match'] equals the latest entry's match."""
    import vintages as vin
    m = ctx["match"]
    latest = max(ctx["entries"], key=lambda e: e["match"])
    prev, now = ctx["prev_now"], ctx["now"]
    frozen = ctx.get("frozen", {})
    champion_b = ctx.get("champion_b", {})

    # Delta vs previous edition (the "news" of this edition)
    deltas_vs_prev = []
    for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
        if t in prev:
            d = 100 * (now[t]["champion"] - prev[t]["champion"])
            if abs(d) >= 0.05:
                deltas_vs_prev.append(f"{t} {d:+.1f}")
    delta_line = ("; ".join(deltas_vs_prev) if deltas_vs_prev
                  else "no contender moved by 0.1 pp or more")

    # Track A vs Frozen: cumulative shift from baseline
    deltas_af = []
    for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
        if t in frozen:
            d = 100 * (now[t]["champion"] - frozen[t].get("champion", 0.0))
            if abs(d) >= 0.05:
                deltas_af.append(f"{t} {d:+.1f}")
    delta_af = ("; ".join(deltas_af) if deltas_af
                else "no contender has moved 0.1 pp or more from baseline")

    # Track B vs Track A: gap between the two tracks
    b_vs_a_line = ""
    if champion_b:
        deltas_ba = []
        for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
            if t in champion_b:
                d = 100 * (champion_b[t] - now[t]["champion"])
                if abs(d) >= 0.05:
                    deltas_ba.append(f"{t} {d:+.1f}")
        delta_ba = ("; ".join(deltas_ba) if deltas_ba
                    else "no contender diverged by 0.1 pp or more between tracks")
        b_vs_a_line = f"\n\nTrack~B vs.\\ Track~A: {delta_ba}."
    imp_lines = "\n".join(
        f"{i['fixture']} & {'/'.join(_pct(p) for p in i['lock_HDA'])} & "
        f"{'/'.join(_pct(p) for p in i['learn_HDA'])} \\\\"
        for i in ctx["implications"])
    imp_block = ("" if not ctx["implications"] else
        "\\paragraph{Implications for upcoming fixtures.} Frozen odds are the "
        "pre-kickoff baseline (they move only through qualification scenarios); "
        "Track~B odds incorporate live Elo and bookmaker signals.\n\n"
        "\\begin{center}\\begin{footnotesize}\\begin{tabular}"
        "{p{0.40\\textwidth}p{0.22\\textwidth}p{0.22\\textwidth}}\\toprule\n"
        "Fixture & Frozen H/D/A (\\%) & Track~B H/D/A (\\%) \\\\\n\\midrule\n"
        + imp_lines + "\n\\bottomrule\\end{tabular}\\end{footnotesize}\\end{center}\n\n")
    return (
        f"\\subsection{{Revision report: edition M{m:03d}}}\\label{{sec:revreport}}\n"
        f"\\paragraph{{The data release.}} Match {latest['match']}, "
        f"{latest['fixture']}: predicted {latest['pre']['pick'][0]}--"
        f"{latest['pre']['pick'][1]}, actual {latest['result'][0]}--"
        f"{latest['result'][1]}; {latest['post']['points']} of 3 points, Brier "
        f"{latest['post']['brier']:.3f}, {latest['post']['info_bits']:.3f} bits.\n\n"
        + _cumulative_stats_table(
            ctx["entries"], ctx["match_stats"],
            ctx.get("expectations", [])) + "\n\n"
        f"\\paragraph{{Forecast revision (vs.\\ edition M{ctx['vintages_rows'][-2]['edition']:03d}).}} "
        f"Champion-probability movement (vs.\\ previous edition): {delta_line}.\n\n"
        f"Track~A vs.\\ Frozen: {delta_af}.{b_vs_a_line}\n\n"
        + imp_block +
        "\\paragraph{Forecast vintages.} One column per issued edition; the "
        "locked M000 column never changes.\n\n"
        + vin.latex_table(ctx["vintages_rows"]))


# ---- new units (design spec 2026-06-13) ----

def abstract_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_abstract_live(ctx, use_api)
    return text


def intro_data_note_unit(ctx, use_api=False):
    text, _ = _ds.draft_intro_data_note(ctx, use_api)
    return text


def simulation_note_unit(ctx, use_api=False):
    text, _ = _ds.draft_simulation_note(ctx, use_api)
    return text


def data_revealed_unit(ctx, use_api=False):
    text, _ = _ds.draft_data_revealed(ctx, use_api)
    validate_labels("data_revealed", text, ["tab:live_data_revealed"])
    return text


def sec36_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_sec36_live(ctx, use_api)
    return text


def robustness_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_robustness_live(ctx, use_api)
    validate_labels("robustness_live", text, ["sec:live_robust"])
    return text


def failure_analysis_unit(ctx, use_api=False):
    text, _ = _ds.draft_failure_analysis(ctx, use_api)
    validate_labels("failure_analysis", text, ["sec:live_failure"])
    return text


def discussion_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_discussion_live(ctx, use_api)
    return text


def champdist_live_unit(ctx):
    """Figure block: live champion probability distribution."""
    return (
        "\\begin{figure}[!t]\n"
        "  \\caption{Champion probability distribution, conditioned on "
        "\\liveDocumented{} results (live edition M\\liveEditionNum{})}"
        "\\label{fig:live_champdist}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_champdist.pdf}\\par}\n"
        "  \\small\\textit{Note:} The frozen baseline (Figure~\\ref{fig:champdist}) "
        "is unchanged; this figure conditions on all played results.\n"
        "\\end{figure}"
    )


def groupqual_live_unit(ctx):
    """Two figure blocks: Track A and Track B qualification probabilities."""
    return (
        "\\begin{figure}[!t]\n"
        "  \\caption{Qualification probability by team --- Track~A "
        "(conditioned on \\liveDocumented{} results, June~10 ratings frozen; "
        "live edition M\\liveEditionNum{})}\\label{fig:live_groupqual}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_groupqual.pdf}\\par}\n"
        "\\end{figure}\n\n"
        "\\begin{figure}[!t]\n"
        "  \\caption{Qualification probability by team --- Track~B "
        "(result-conditioning + live Elo + bookmaker odds; "
        "live edition M\\liveEditionNum{})}\\label{fig:live_groupqual_b}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_groupqual_b.pdf}\\par}\n"
        "\\end{figure}"
    )


_R32_PAIRS = [
    # (home, away, match_number) — pre-registered bracket (LEFT then RIGHT half)
    ("Germany",       "Paraguay",              73),
    ("France",        "Sweden",                74),
    ("South Korea",   "Canada",                75),
    ("Netherlands",   "Morocco",               76),
    ("Colombia",      "Croatia",               77),
    ("Spain",         "Austria",               78),
    ("United States", "Bosnia and Herzegovina", 79),
    ("Belgium",       "Czechia",               80),
    ("Brazil",        "Japan",                 81),
    ("Ecuador",       "Norway",                82),
    ("Mexico",        "Ivory Coast",           83),
    ("England",       "Algeria",               84),
    ("Argentina",     "Uruguay",               85),
    ("Turkey",        "Egypt",                 86),
    ("Switzerland",   "Iran",                  87),
    ("Portugal",      "Senegal",               88),
]


def _slot_status(frozen_pct, track_b_pct):
    drop = frozen_pct - track_b_pct
    if drop < 5:
        return "\\checkmark"
    if drop <= 20:
        return "$\\triangle$"
    return "$\\times$"


def bracket_live_unit(ctx):
    """Knockout bracket: slot risk table during group stage, live figure once KO begins."""
    ko_results = ctx.get("results", {}).get("ko", {})
    if ko_results:
        return (
            "\\begin{figure}[!t]\n"
            "  \\caption{The submitted bracket through M\\liveEditionNum{}, valued "
            "by champion probability under Track~A (top) and Track~B (bottom); "
            "greyed boxes are teams eliminated by confirmed results}"
            "\\label{fig:live_bracket}\n"
            "  {\\centering\\includegraphics[width=0.92\\textwidth]"
            "{figs/fig_live_bracket_a.pdf}\\par\\smallskip\n"
            "  \\includegraphics[width=0.92\\textwidth]"
            "{figs/fig_live_bracket_b.pdf}\\par}\n"
            "\\end{figure}"
        )
    frozen = ctx.get("frozen", {})
    now = ctx.get("now", {})
    now_b = ctx.get("now_b", {})
    has_b = bool(now_b)

    rows = []
    for home, away, mn in _R32_PAIRS:
        for team in (home, away):
            fr = frozen.get(team, {}).get("advance_KO", 0.0)
            ta = now.get(team, frozen.get(team, {})).get("advance_KO", fr)
            tb = now_b.get(team, {}).get("advance_KO", float("nan")) if has_b else float("nan")
            fr_p, ta_p = round(100 * fr, 1), round(100 * ta, 1)
            tb_str = f"{100 * tb:.1f}" if tb == tb else "--"
            status = _slot_status(fr_p, 100 * tb if tb == tb else fr_p) if has_b else ""
            b_col = f" & {tb_str} & {status}" if has_b else ""
            rows.append(
                f"{team} advance & M{mn} & {fr_p} & {ta_p}{b_col} \\\\"
            )

    if has_b:
        col_spec = "llrrrl"
        hdr = "KO Pick & Slot & Frozen~\\% & Track~A~\\% & Track~B~\\% & Status \\\\"
        note = (
            "Status: \\checkmark{} = Track~B within 5 pp of Frozen; "
            "$\\triangle$ = 5--20 pp drop; $\\times$ = pick reversed ($>$20 pp)."
        )
    else:
        col_spec = "llrr"
        hdr = "KO Pick & Slot & Frozen~\\% & Track~A~\\% \\\\"
        note = ""

    body = "\n".join(rows)
    note_line = f"\n\\smallskip\\begin{{footnotesize}}{note}\\end{{footnotesize}}" if note else ""
    return (
        "\\begin{table}[!t]\n  \\centering\n"
        "  \\caption{R32 slot risk: probability each pre-registered pick "
        "advances from the group stage (live edition M\\liveEditionNum{})"
        "}\\label{tab:live_slot_risk}\n"
        f"  {{\\begin{{footnotesize}}\\begin{{tabular}}{{{col_spec}}}\n"
        f"  \\toprule\n  {hdr}\n  \\midrule\n  {body}\n"
        "  \\bottomrule\\end{tabular}\\end{footnotesize}}"
        + note_line + "\n\\end{table}"
    )


def survival_colcomp_unit(ctx):
    """Appendix B.live: side-by-side Frozen / Track A / Track B survival probabilities.
    Shows F/A/B when ctx['now_b'] is available, F/A otherwise."""
    frozen = ctx["frozen"]
    now = ctx["now"]
    now_b = ctx.get("now_b", {})
    has_b = bool(now_b)
    teams = sorted(now, key=lambda t: (-now[t]["champion"], -now[t]["advance_KO"]))
    stages = ["advance_KO", "R16", "QF", "SF", "final", "champion"]
    headers = "Team & KO & R16 & QF & SF & Final & Champion \\\\"

    def triple(t, stage):
        f = frozen.get(t, {}).get(stage, 0.0)
        a = now[t].get(stage, 0.0)
        delta = abs(a - f)
        a_str = f"\\textbf{{{_pct(a)}}}" if delta > 3.0 else _pct(a)
        if has_b and t in now_b:
            b = now_b[t].get(stage, 0.0)
            return f"{_pct(f)}/{a_str}/{_pct(b)}"
        return f"{_pct(f)}/{a_str}"

    rows = [
        t + " & " + " & ".join(triple(t, s) for s in stages) + " \\\\"
        for t in teams if t in frozen
    ]
    if has_b:
        note = "Each cell shows F/A/B = Frozen\\%{}/Track~A\\%/Track~B\\%; bold Track~A when $|\\Delta| > 3$ pp."
        title = "Frozen / Track~A / Track~B stage probabilities, all 48 teams"
    else:
        note = "Each cell shows Frozen\\%{}~/{}Track~A\\%; bold Track~A when $|\\Delta| > 3$ pp."
        title = "Frozen vs.\\ Track~A stage probabilities, all 48 teams"
    return (
        "\\section*{Appendix B.live\\quad The same distribution, "
        "all three tracks side by side}\\label{app:survlive}\n"
        + note + "\n\n"
        "\\begin{scriptsize}\n\\begin{longtable}{lrrrrrr}\n"
        "\\caption{" + title + " "
        "(live edition M\\liveEditionNum{})}\\label{tab:live_survcomp}\\\\\n"
        "\\toprule\n" + headers + "\n\\midrule\n"
        "\\endfirsthead\n"
        "\\toprule\n" + headers + "\n\\midrule\n"
        "\\endhead\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n\\end{longtable}\n\\end{scriptsize}"
    )


def market_snap_unit(ctx):
    """§4.7 live market snapshot table + status paragraph.
    Requires ctx['market'] (dict team→prob) and ctx['champion_b'] (dict team→prob)."""
    now = ctx.get("now", {})
    frozen = ctx.get("frozen", {})
    champion_b = ctx.get("champion_b", {})
    market = ctx.get("market")
    teams = sorted(now, key=lambda t: -now[t].get("champion", 0))[:8]
    rows = []
    for t in teams:
        frz_pct = _pct(frozen.get(t, {}).get("champion", 0))
        a_pct = _pct(now[t].get("champion", 0))
        b_pct = _pct(champion_b.get(t, 0)) if champion_b else "---"
        mkt_pct = _pct(market[t]) if market and t in market else "---"
        delta = (f"{100*(now[t].get('champion', 0) - frozen.get(t, {}).get('champion', now[t].get('champion', 0))):+.1f}"
                 if t in frozen else "---")
        rows.append(f"{t} & {frz_pct} & {a_pct} & {b_pct} & {mkt_pct} & {delta} \\\\")
    table = (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Live champion-probability snapshot (live edition "
        "M\\liveEditionNum{})}\\label{tab:live_market_snap}\n"
        "\\begin{footnotesize}\\begin{tabular}{lrrrrr}\\toprule\n"
        "Team & Frozen (\\%) & Track~A (\\%) & Track~B (\\%) & "
        "Market (\\%) & $\\Delta$ (A$-$Frozen) \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\\end{footnotesize}\\end{table}"
    )
    if market:
        status = (
            "Market and Track~A rank orderings broadly agree at this edition; "
            "divergence tracking (who-moves-first) continues through knockout stages."
        )
        fig_block = (
            "\n\n"
            "\\begin{figure}[!t]\n"
            "  \\caption{Four-bar champion probability: Frozen / Track~A / Track~B / Market, "
            "top contenders (live edition M\\liveEditionNum{})}\\label{fig:live_market}\n"
            "  {\\centering\\includegraphics[width=0.94\\textwidth]"
            "{figs/fig_live_market.pdf}\\par}\n"
            "\\end{figure}"
        )
    else:
        status = "Market-probability data are not yet available for this edition."
        fig_block = ""
    return table + "\n\n" + status + fig_block


def _abbrev_team(t, n=14):
    """Match the locked Table 13 abbreviation style (e.g. 'Bosnia and He.')."""
    return t if len(t) <= n else t[:n - 1].rstrip() + "."


def _finish_cells(d):
    """Three finishing-position cells + Qual as integer percents from a stage
    dict carrying first/second/third_adv/advance_KO, or four '--' when absent."""
    if not d:
        return ["--", "--", "--", "--"]
    return [f"{100 * d.get('first', 0):.0f}",
            f"{100 * d.get('second', 0):.0f}",
            f"{100 * d.get('third_adv', 0):.0f}",
            f"\\textbf{{{100 * d.get('advance_KO', 0):.0f}}}"]


def groupqual_table_unit(ctx):
    """Table 10: three-panel finishing-position table (Frozen / Track A / Track B),
    14 columns: Grp, Team, then 1st/2nd/3rd*/Qual for each track. Frozen panel is
    the locked Table 13 (ctx['frozen_finish'], 100k sims); Track A/B carry the
    finishing-position keys added by condition.conditional_probs."""
    frozen_finish = ctx.get("frozen_finish", {})   # {grp: {team: {p1,p2,p3adv,qual}}}
    now = ctx.get("now", {})
    now_b = ctx.get("now_b", {})
    group_state = ctx.get("group_state", [])

    if not group_state:
        return (r"\textit{Group-state not yet available; qualification table "
                r"will appear once matches are recorded.}")

    def _frozen_cells(grp, t):
        d = frozen_finish.get(grp, {}).get(t)
        if not d:
            return ["--", "--", "--", "--"]
        return [f"{100 * d.get('p1', 0):.0f}", f"{100 * d.get('p2', 0):.0f}",
                f"{100 * d.get('p3adv', 0):.0f}",
                f"\\textbf{{{100 * d.get('qual', 0):.0f}}}"]

    rows = []
    for g in group_state:
        grp = g["group"]
        teams = sorted(
            [r["team"] for r in g["rows"]],
            key=lambda t: -now.get(t, {}).get("advance_KO",
                          frozen_finish.get(grp, {}).get(t, {}).get("qual", 0)))
        for i, t in enumerate(teams):
            grp_col = grp if i == 0 else ""
            cells = (_frozen_cells(grp, t)
                     + _finish_cells(now.get(t))
                     + _finish_cells(now_b.get(t)))
            rows.append(f"{grp_col} & {_abbrev_team(t)} & " + " & ".join(cells) + " \\\\")
        rows.append("\\addlinespace")
    if rows and rows[-1] == "\\addlinespace":
        rows.pop()

    note = ("1st / 2nd / 3rd$^{*}$ / Qual = probability of winning the group, "
            "finishing second, advancing as a best third-placed team, and "
            "qualifying in total. Frozen = pre-kickoff lock ($N$=100{,}000, "
            "never changes); Track~A = result-conditioned, June~10 ratings "
            "($N$=50{,}000); Track~B = result-conditioning + live Elo + "
            "bookmaker odds ($N$=50{,}000). Dashes mark a track not yet "
            "populated for that edition.")

    panel_hdr = ("\\multicolumn{4}{c}{Frozen} & \\multicolumn{4}{c}{Track~A} & "
                 "\\multicolumn{4}{c}{Track~B} \\\\\n"
                 "\\cmidrule(lr){3-6}\\cmidrule(lr){7-10}\\cmidrule(lr){11-14}\n")
    sub_hdr = ("Grp & Team & " + " & ".join(
        ["1st & 2nd & 3rd$^{*}$ & Qual"] * 3) + " \\\\\n\\midrule\n")

    return (
        "\\begin{table}[!t]\\centering\n"
        "\\caption{Group finishing-position probabilities --- Frozen / Track~A "
        "/ Track~B, all teams (live edition M\\liveEditionNum{})}"
        "\\label{tab:live_groupqual_three}\n"
        "{\\setlength{\\tabcolsep}{3pt}\\scriptsize\\begin{threeparttable}\n"
        "\\begin{tabular}{llrrrrrrrrrrrr}\\toprule\n"
        " & & " + panel_hdr
        + sub_hdr
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\n"
        "\\begin{tablenotes}\\notesize\n"
        f"\\item \\textit{{Notes}}: {note}\n"
        "\\end{tablenotes}\\end{threeparttable}}\n\\end{table}"
    )


def fixture_risk_unit(ctx):
    """Table 11: Decisive upcoming fixtures — teams on the qualification bubble
    (10\\% < Track~A advance~\\% < 90\\%) with Frozen and Track~B H/D/A odds."""
    now = ctx.get("now", {})
    expectations = ctx.get("expectations", [])
    results = ctx.get("results", {})
    implications = ctx.get("implications", [])
    group_state = ctx.get("group_state", [])

    played = set(results.get("group", {}).keys())
    imp_by_fixture = {i["fixture"]: i for i in implications}

    rows = []
    for g in group_state:
        grp = g["group"]
        for e in expectations:
            if e.get("group") != grp or str(e["match"]) in played:
                continue
            home, away = e["home"], e["away"]
            h_adv = now.get(home, {}).get("advance_KO", 0)
            a_adv = now.get(away, {}).get("advance_KO", 0)
            bubble = [(t, adv) for t, adv in [(home, h_adv), (away, a_adv)]
                      if 0.10 < adv < 0.90]
            if not bubble:
                continue
            fixture = f"{home} v {away}"
            bubble_str = "; ".join(f"{t} {_pct(adv)}\\%" for t, adv in bubble)
            lock_str = "/".join(_pct(p) for p in e["probs_HDA"])
            imp = imp_by_fixture.get(fixture)
            b_hda = "/".join(_pct(p) for p in imp["learn_HDA"]) if imp else "--"
            rows.append(
                f"  {grp} & {fixture} & {bubble_str} & {lock_str} & {b_hda} \\\\"
            )

    if not rows:
        return ("\\textit{No upcoming group fixtures with bubble teams; all "
                "qualification spots are effectively decided at this stage.}")

    return (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Decisive upcoming fixtures --- bubble teams and outcome odds "
        "(live edition M\\liveEditionNum{})}\\label{tab:live_fixture_risk}\n"
        "\\begin{footnotesize}\\begin{tabular}{lp{0.28\\textwidth}p{0.22\\textwidth}cc}\\toprule\n"
        "Grp & Fixture & Bubble team(s) (Track~A Qual\\%) & "
        "Frozen H/D/A (\\%) & Track~B H/D/A (\\%) \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\\end{footnotesize}\\end{table}"
    )


# Pre-registered decisive fixture + primary forecast risk per group, copied
# verbatim from the locked Table~\ref{tab:watchrisk}. These never change; the
# live tracker (Table 11) scores their status against the results so far.
_PREREG_RISK = {
    "A": ("South Korea v Czechia, MD1", "Czechia (68\\% qual.) takes second ahead of South Korea"),
    "B": ("Switzerland v Canada, MD3", "Host Canada (88\\%) wins the group outright"),
    "C": ("Scotland v Morocco, MD2", "Scotland (69\\%) overtakes Morocco for second"),
    "D": ("Turkey v United States, MD3", "Turkey tops the group and reroutes the bracket"),
    "E": ("Ecuador v Germany, MD3", "Ecuador (88\\%, Elo 1935) wins the group, not second"),
    "F": ("Netherlands v Japan, MD1", "Japan (76\\%) wins the group ahead of the Netherlands"),
    "G": ("Egypt v Iran, MD3", "Iran (63\\%) edges Egypt for second"),
    "H": ("Cape Verde v Saudi Arabia (3rd-place race)", "Neither third-placer qualifies; Uruguay slips to second"),
    "I": ("Norway v Senegal, MD2", "Senegal (82\\%) beats Norway and takes second"),
    "J": ("Algeria v Austria, MD3", "Algeria (57\\%) overtakes Austria for second"),
    "K": ("Colombia v Portugal, MD3", "The Elo tie holds and Colombia (94\\%) tops the group"),
    "L": ("England v Croatia, MD1", "Croatia (96\\%) wins the group instead of England"),
}


def _frozen_top2(grp, frozen_finish):
    """The submitted group winner and runner-up: argmax p1, then argmax p2."""
    teams = frozen_finish.get(grp, {})
    if not teams:
        return []
    first = max(teams, key=lambda t: teams[t].get("p1", 0))
    rest = [t for t in teams if t != first]
    if not rest:
        return [first]
    second = max(rest, key=lambda t: teams[t].get("p2", 0))
    return [first, second]


def _current_top2(g, now):
    """Current top two: actual standings when the group is complete, else the
    Track~A advance-probability ranking."""
    if g["played"] >= g["total"]:
        return [r["team"] for r in g["rows"][:2]]
    teams = [r["team"] for r in g["rows"]]
    return sorted(teams, key=lambda t: -now.get(t, {}).get("advance_KO", 0))[:2]


def risk_tracker_unit(ctx):
    """Table 11: live status of each group's pre-registered forecast risk.
    Status is scored programmatically from the submitted top two (Frozen) vs the
    current top two (actual standings if the group is complete, else Track~A)."""
    frozen_finish = ctx.get("frozen_finish", {})
    now = ctx.get("now", {})
    group_state = {g["group"]: g for g in ctx.get("group_state", [])}

    if not frozen_finish:
        return (r"\textit{Risk tracker unavailable; frozen finishing-position "
                r"baseline not loaded for this edition.}")

    rows = []
    for grp in "ABCDEFGHIJKL":
        fixture, risk = _PREREG_RISK[grp]
        g = group_state.get(grp)
        sub = _frozen_top2(grp, frozen_finish)
        if g is None or not sub:
            status, emerging = "$\\triangle$ Pending", "--"
        else:
            cur = _current_top2(g, now)
            held = set(cur) == set(sub)
            complete = g["played"] >= g["total"]
            if complete and held:
                status = "\\checkmark\\ Resolved"
            elif complete and not held:
                status = "$\\times$ Reversed"
            elif held:
                status = "$\\triangle$ Pending"
            else:
                status = "$\\triangle$ At risk"
            if not held:
                gained = [t for t in cur if t not in sub]
                dropped = [t for t in sub if t not in cur]
                if gained and dropped:
                    emerging = (f"Track~A now has {_abbrev_team(gained[0])} in the "
                                f"top two over {_abbrev_team(dropped[0])}")
                else:
                    emerging = "Track~A order differs from the submitted top two"
            else:
                emerging = "--"
        rows.append(f"  {grp} & {fixture} & {risk} & {status} & {emerging} \\\\")

    return (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Pre-registered group risks: live status against the results "
        "so far (live edition M\\liveEditionNum{})}\\label{tab:live_risk_tracker}\n"
        "\\begin{footnotesize}\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}"
        "lp{3.1cm}p{4.6cm}p{1.7cm}p{3.0cm}}\\toprule\n"
        "Grp & Decisive fixture & Pre-registered risk & Status & Emerging issue \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular*}\\end{footnotesize}\n"
        "\\begin{footnotesize}\\textit{Notes}: Status compares the submitted top "
        "two (Frozen modal 1st/2nd) with the current top two --- actual standings "
        "once a group is complete, otherwise the Track~A advance ranking. "
        "\\checkmark\\ Resolved = held at completion; $\\times$ Reversed = a "
        "submitted qualifier displaced; $\\triangle$ = group still open.\\end{footnotesize}"
        "\n\\end{table}"
    )
