"""Render every living unit of the paper to its own generated file under
paper/live/. The skeleton WC2026_paper.tex carries only permanent \\input lines
and is never written by the pipeline; skeleton_hash + data/skeleton_sha256.txt
prove it byte-identical on every run. Pure renderers: context in, tex out."""
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import render_evolution as rev
import poisson_model as pm
import draft_sections as _ds

HEADER = "% GENERATED by scripts/render_live.py — do not edit by hand.\n"


def skeleton_hash(tex):
    return hashlib.sha256(tex.encode()).hexdigest()


def write_unit(live_dir, name, content):
    Path(live_dir).mkdir(parents=True, exist_ok=True)
    (Path(live_dir) / f"{name}.tex").write_text(HEADER + content + "\n",
                                                encoding="utf-8")


def validate_labels(name, content, required):
    """Raise ValueError if any required \\label{tag} is absent from content."""
    for label in required:
        if f"\\label{{{label}}}" not in content:
            raise ValueError(
                f"render_live: {name}.tex missing \\label{{{label}}} — "
                f"add it to the generator or the prompt template")


def outcome_probs(lh, la):
    """Normalized P(H/D/A) for display (poisson_model's raw triple loses the
    truncated mass beyond MAX_G goals)."""
    ph, pd, pa = pm.outcome_probs(lh, la)
    s = ph + pd + pa
    return ph / s, pd / s, pa / s


def _pct(x):
    return f"{100 * x:.1f}"


# ---- ported units (reuse render_evolution's pure builders) ----

def ledger(entries):
    return rev.ledger_table(entries)


def narrative_unit(entries):
    return rev.narrative(entries)


def trajfig_unit(entries, live_fig):
    return rev.trajfig(entries, live_fig)


def champ_table_unit(frozen, now, n_results, champion_b=None):
    return rev.champ_table(frozen, now, n_results, champion_b=champion_b)


def divergence_unit(frozen, now, entries, group_state, champion_b=None, now_b=None):
    played = [g for g in group_state if g["played"]]
    return rev.divergence_section(frozen, now, entries, played, champion_b=champion_b, now_b=now_b)


# ---- new units ----

def tracker(group_state, frozen, now):
    """Main-text 'state of the group stage': one row per group. frozen is
    accepted for signature symmetry with the other units; the table shows
    only current values."""
    rows = []
    for g in group_state:
        top2 = g["rows"][:2]
        if g["played"]:
            standing = "; ".join(f"{r['team']} {r['Pts']}" for r in top2)
        else:
            standing = "--"
        leaders = sorted((r for r in g["rows"] if r["team"] in now),
                         key=lambda r: -now[r["team"]]["advance_KO"])[:2]
        qual = "; ".join(
            f"{r['team']} {_pct(now[r['team']]['advance_KO'])}" for r in leaders)
        rows.append(f"{g['group']} & {g['played']}/{g['total']} & {standing} & {qual} \\\\")
    return (
        "\\begin{table}[!t]\n  \\centering\n"
        "  \\caption{State of the group stage (live edition)}\\label{tab:tracker}\n"
        "  \\begin{footnotesize}\n"
        "  {\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} clll}\n"
        "    \\toprule\n"
        "    Group & Played & Standings (top two, real points) & Advance now (top two) \\\\\n"
        "    \\midrule\n    " + "\n    ".join(rows) + "\n"
        "    \\bottomrule\n  \\end{tabular*}}\n  \\end{footnotesize}\n\\end{table}")


def group_box(g_state, results, expectations, frozen, now, now_b=None, implications=None):
    """Appendix-A living box for one group: unified round-robin matrix with
    actual/prediction results + right-side standing + qual columns.
    now_b: Track B full stage probs {team: {advance_KO,...}}.
    implications: list of {fixture, lock_HDA, learn_HDA} for upcoming fixtures."""
    grp = g_state["group"]
    teams = [r["team"] for r in g_state["rows"]]
    exps = {(e["home"], e["away"]): e
            for e in expectations if e.get("group") == grp}
    res_by_match = results["group"]

    if not g_state["played"]:
        qual = "; ".join(f"{t} {_pct(frozen[t]['advance_KO'])}"
                         for t in teams if t in frozen)
        return (f"\\paragraph{{Group {grp} — live.}} No results yet; "
                f"Frozen qualification odds: {qual}.")

    def _sgn(d): return 1 if d > 0 else (-1 if d < 0 else 0)

    # Index implications by fixture name for Track B H/D/A lookup
    imp_by_fixture = {i["fixture"]: i for i in (implications or [])}

    # Build round-robin matrix: rows = teams, cols = opponent teams
    # Right-side columns: Actual W/D/L/Pts/Qual% | Frozen Qual% | Track A Qual% | Track B Qual%
    n = len(teams)
    col_spec = "l" + "c" * n + "rrrr"
    header_teams = " & ".join(f"\\tiny {t}" for t in teams)
    header = (f" & {header_teams} & \\makecell{{Actual\\\\W/D/L/Pts/Q\\%}} & "
              f"Q\\%(F) & Q\\%(A) & Q\\%(B) \\\\")

    matrix_rows = []
    for home in teams:
        cells = []
        for away in teams:
            if home == away:
                cells.append("---")
                continue
            e = exps.get((home, away)) or exps.get((away, home))
            if e is None:
                cells.append("?")
                continue
            match_key = str(e["match"])
            res = res_by_match.get(match_key)
            if res:
                # played: actual score + correct/wrong indicator
                if e["home"] == home:
                    score = f"{res[0]}--{res[1]}"
                    pick = e["pick"]
                    correct = _sgn(pick[0] - pick[1]) == _sgn(res[0] - res[1])
                else:
                    score = f"{res[1]}--{res[0]}"
                    pick = e["pick"]
                    correct = _sgn(pick[0] - pick[1]) == _sgn(res[0] - res[1])
                icon = r"$\checkmark$" if correct else r"$\times$"
                cells.append(f"\\textbf{{{score}}}{icon}")
            else:
                # upcoming: Frozen H/D/A; add Track B line if implications available
                ph, pd, pa = e["probs_HDA"]
                fixture_name = f"{e['home']} v {e['away']}"
                imp = imp_by_fixture.get(fixture_name)
                if imp:
                    bh, bd, ba = imp["learn_HDA"]
                    if e["home"] == home:
                        cells.append(
                            f"\\tiny F:{_pct(ph)}/{_pct(pd)}/{_pct(pa)}"
                            f"\\\\B:{_pct(bh)}/{_pct(bd)}/{_pct(ba)}")
                    else:
                        cells.append(
                            f"\\tiny F:{_pct(pa)}/{_pct(pd)}/{_pct(ph)}"
                            f"\\\\B:{_pct(ba)}/{_pct(bd)}/{_pct(bh)}")
                else:
                    if e["home"] == home:
                        cells.append(f"\\tiny {_pct(ph)}/{_pct(pd)}/{_pct(pa)}")
                    else:
                        cells.append(f"\\tiny {_pct(pa)}/{_pct(pd)}/{_pct(ph)}")

        # right-side standing columns
        row_data = next((r for r in g_state["rows"] if r["team"] == home), {})
        w, d, l = row_data.get("W", 0), row_data.get("D", 0), row_data.get("L", 0)
        pts = row_data.get("Pts", 0)
        qual_a = _pct(now[home]["advance_KO"]) if home in now else "--"
        qual_f = _pct(frozen[home]["advance_KO"]) if home in frozen else "--"
        qual_b = _pct(now_b[home]["advance_KO"]) if now_b and home in now_b else "--"
        actual_str = f"{w}/{d}/{l}/{pts}/{qual_a}\\%"
        matrix_rows.append(
            f"\\tiny {home} & " + " & ".join(cells)
            + f" & \\tiny {actual_str} & \\tiny {qual_f}\\% "
            f"& \\tiny {qual_a}\\% & \\tiny {qual_b}\\% \\\\"
        )

    # Remaining fixtures block: upcoming matches in this group
    remaining_lines = []
    for e in expectations:
        if e.get("group") != grp or str(e["match"]) in res_by_match:
            continue
        fixture_name = f"{e['home']} v {e['away']}"
        lock_str = "/".join(_pct(p) for p in e["probs_HDA"])
        imp = imp_by_fixture.get(fixture_name)
        learn_str = "/".join(_pct(p) for p in imp["learn_HDA"]) if imp else "--"
        remaining_lines.append(f"{fixture_name} & {lock_str} & {learn_str} \\\\")

    fixtures_block = ""
    if remaining_lines:
        fixtures_block = (
            "\n\\smallskip\n"
            "\\begin{footnotesize}\n"
            "\\begin{tabular}{lcc}\\toprule\n"
            "Fixture & Frozen H/D/A (\\%) & Track~B H/D/A (\\%) \\\\\n"
            "\\midrule\n"
            + "\n".join(remaining_lines) + "\n"
            "\\bottomrule\\end{tabular}\n"
            "\\end{footnotesize}"
        )

    return (
        f"\\paragraph{{Group {grp} — live ({g_state['played']} of "
        f"{g_state['total']} played).}}\n"
        "\\begin{footnotesize}\n"
        f"\\begin{{tabular}}{{{col_spec}}}\n"
        "\\toprule\n"
        f"{header}\n"
        "\\midrule\n"
        + "\n".join(matrix_rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{footnotesize}"
        + fixtures_block
    )


def survival_unit(frozen, now):
    """Appendix-B 'now' restatement of the stage-by-stage outcome table.
    frozen is intentionally unused: the locked table sits directly above in
    the paper, so only the conditioned values are printed here."""
    teams = sorted(now, key=lambda t: (-now[t]["champion"], -now[t]["advance_KO"]))
    rows = [f"{t} & {_pct(now[t]['advance_KO'])} & {_pct(now[t]['R16'])} & "
            f"{_pct(now[t]['QF'])} & {_pct(now[t]['SF'])} & "
            f"{_pct(now[t]['final'])} & {_pct(now[t]['champion'])} \\\\"
            for t in teams]
    return (
        "\\subsection*{B.live \\quad The same distribution, conditioned on the "
        "results so far}\n"
        "The table restates the stage-reached probabilities of the locked table "
        "above, conditioned on every result revealed to date; the locked table "
        "never changes, so the pair is directly comparable.\n\n"
        "\\begin{footnotesize}\n\\begin{longtable}{lrrrrrr}\n"
        "\\caption{Stage-reached probabilities conditioned on results so far "
        "(live edition)}\\label{tab:live_survival}\\\\\n"
        "\\toprule\nTeam & KO & R16 & QF & SF & Final & Champion \\\\\n\\midrule\n"
        "\\endfirsthead\n"
        "\\toprule\nTeam & KO & R16 & QF & SF & Final & Champion \\\\\n\\midrule\n"
        "\\endhead\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{longtable}\n\\end{footnotesize}")


def two_track_unit(two_track, learning, fig, info_snapshot=None, track_a=None):
    """The live A-vs-B: Frozen / Track A / Track B champion odds and Elo drift.
    track_a: dict of {team: {champion: prob, ...}} (Track A / now_probs).
    info_snapshot: no longer used here (provenance moved to data_revealed)."""
    if two_track is None:
        return ("\\textit{Two-track live results begin with the first match "
                "whose box score is collected.}")
    teams = sorted(two_track["frozen"], key=lambda t: -two_track["frozen"][t])[:8]
    if track_a is not None:
        rows = "\n".join(
            f"{t} & {_pct(two_track['frozen'][t])} & "
            f"{_pct(track_a.get(t, {}).get('champion', 0.0))} & "
            f"{_pct(two_track['learning'].get(t, 0.0))} & "
            f"{100*(track_a.get(t, {}).get('champion', 0.0) - two_track['frozen'][t]):+.1f} \\\\"
            for t in teams)
        header = ("Team & Frozen (\\%) & Track~A (\\%) & Track~B (\\%) & "
                  "$\\Delta$ (A$-$Frozen, pp) \\\\\n\\midrule\n")
        col_spec = "lrrrr"
    else:
        rows = "\n".join(
            f"{t} & {_pct(two_track['frozen'][t])} & "
            f"{_pct(two_track['learning'].get(t, 0.0))} & "
            f"{100*(two_track['learning'].get(t, 0.0) - two_track['frozen'][t]):+.1f} \\\\"
            for t in teams)
        header = "Team & Frozen (\\%) & Track~B (\\%) & $\\Delta$ (pp) \\\\\n\\midrule\n"
        col_spec = "lrrr"
    drifts = sorted(learning["drift"].items(), key=lambda kv: -abs(kv[1]))[:8]
    drift_rows = "\n".join(f"{t} & {d:+.1f} \\\\" for t, d in drifts)
    pend = (f" Stats pending for matches: "
            f"{', '.join(f'M{m:03d}' for m in learning['pending'])}."
            if learning["pending"] else "")
    fig_block = ("\\begin{figure}[!t]\n  \\caption{Two tracks live: Frozen vs "
                 "Track~A vs Track~B champion paths}\\label{fig:twotracklive}\n"
                 "  {\\centering\\includegraphics[width=0.94\\textwidth]"
                 "{figs/fig_two_track_live.pdf}\\par}\n\\end{figure}\n" if fig else "")
    n = len(learning["processed"])

    return (
        "\\subsection{The two tracks live: 2026 as it speaks}"
          "\\label{sec:twotracklive}\n"
          f"The pre-registered A-vs-B study of Appendix~D, running on the real "
          f"tournament: after each match the observed shot performance "
          f"($\\lambda_{{\\mathrm{{obs}}}}$, Appendix~D.2) updates Track~B's "
          f"ratings (k=50, locked), while Track~A re-conditions "
          f"on results alone. {n} match(es) processed so far.{pend}\n\n"
        + fig_block
        + "\\begin{footnotesize}\n"
          f"\\begin{{tabular}}{{{col_spec}}}\n\\toprule\n"
        + header
        + rows
        + "\n\\bottomrule\n\\end{tabular}\\qquad\n"
          "\\begin{tabular}{lr}\n\\toprule\nTeam & Drift (Elo) \\\\\n\\midrule\n"
        + drift_rows
        + "\n\\bottomrule\n\\end{tabular}\n\\end{footnotesize}"
    )


def _stats_release(match, match_stats, learning):
    s = match_stats.get(match)
    rec = next((r for r in learning["processed"] if r["match"] == match), None)
    if s is None:
        return ("\\textit{Box-score statistics for this match are pending; the "
                "performance analysis will appear in the next edition.}")
    def _row(label, key, fmt="{:.0f}"):
        return (f"{label} & " + fmt.format(s['home'][key]) + " & "
                + fmt.format(s['away'][key]) + " \\\\")
    lines = [_row("Shots", "total_shots"), _row("On target", "sot")]
    if (s["home"].get("possession") is not None
            and s["away"].get("possession") is not None):
        lines.append(_row("Possession (\\%)", "possession", "{:.0f}"))
    perf = ""
    if rec:
        perf = (f"\\\\[2pt] Performance vs.\\ expectation: "
                f"$\\lambda_{{\\mathrm{{obs}}}}$ = {rec['lam_obs']['home']:.2f} / "
                f"{rec['lam_obs']['away']:.2f} against "
                f"$\\lambda_{{\\mathrm{{exp}}}}$ = {rec['lam_exp']['home']:.2f} / "
                f"{rec['lam_exp']['away']:.2f} "
                f"({rec['lam_obs']['source']} signal); the learning track moves "
                f"{rec['home']} by {rec['drift_after'].get(rec['home'], 0):+.1f} and "
                f"{rec['away']} by {rec['drift_after'].get(rec['away'], 0):+.1f} Elo.")
    return ("\\begin{table}[!h]\\centering\n"
            "\\caption{Match statistics (live edition M\\liveEditionNum{})}\\label{tab:live_edition_snapshot}\n"
            "\\begin{footnotesize}\\begin{tabular}{lrr}\\toprule\n"
            f" & {s['home']['team']} & {s['away']['team']} \\\\\n\\midrule\n"
            + "\n".join(lines) + "\n\\bottomrule\\end{tabular}\\end{footnotesize}"
            + perf
            + "\n\\end{table}")


def _cumulative_stats_table(entries, match_stats, expectations):
    """Table 7: one row per played match, grows with each edition.
    Columns: Game | Shots H–A | On target H–A | Poss H–A | Frozen H/D/A | Track B H/D/A.
    Track B H/D/A is stored in entry['pre']['probs_HDA_b'] at documentation time
    (pre-match learn_ratings); '--' for entries documented before this feature."""
    rows = []
    exp_by_match = {e["match"]: e for e in expectations}
    has_b = any(e.get("pre", {}).get("probs_HDA_b") for e in entries)
    for e in sorted(entries, key=lambda x: x["match"]):
        m = e["match"]
        s = match_stats.get(m)
        if s is None:
            continue
        sh = s["home"].get("total_shots", "--")
        sa = s["away"].get("total_shots", "--")
        oh = s["home"].get("sot", "--")
        oa = s["away"].get("sot", "--")
        ph = s["home"].get("possession")
        pa = s["away"].get("possession")
        poss = f"{ph:.0f}--{pa:.0f}" if ph is not None and pa is not None else "--"
        exp = exp_by_match.get(m)
        hda = "/".join(_pct(p) for p in exp["probs_HDA"]) if exp else "--"
        hda_b_raw = e.get("pre", {}).get("probs_HDA_b")
        hda_b = "/".join(_pct(p) for p in hda_b_raw) if hda_b_raw else "--"
        if has_b:
            rows.append(
                f"M{m} {e['fixture']} & {sh}--{sa} & {oh}--{oa} & {poss} & {hda} & {hda_b} \\\\"
            )
        else:
            rows.append(
                f"M{m} {e['fixture']} & {sh}--{sa} & {oh}--{oa} & {poss} & {hda} \\\\"
            )
    if not rows:
        return r"\textit{Match statistics pending.}"
    if has_b:
        col_spec = "lccccc"
        header = ("Game & Shots (H--A) & On target (H--A) & Poss\\% (H--A) & "
                  "Frozen H/D/A & Track~B H/D/A \\\\\n")
    else:
        col_spec = "lcccc"
        header = "Game & Shots (H--A) & On target (H--A) & Poss\\% (H--A) & Frozen H/D/A \\\\\n"
    return (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Cumulative match statistics (live edition "
        "M\\liveEditionNum{})}\\label{tab:live_match_stats}\n"
        f"\\begin{{footnotesize}}\\begin{{tabular}}{{{col_spec}}}\\toprule\n"
        + header
        + "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\\end{footnotesize}\n\\end{table}"
    )


def revision_report(ctx):
    """The central-bank release: data release, forecast revision vs the
    previous edition, implications, vintages. Driver contract: ctx
    vintages_rows already contains THIS edition's row (so [-2] is the
    previous edition) and ctx['match'] equals the latest entry's match."""
    import vintages as vin
    m = ctx["match"]
    latest = max(ctx["entries"], key=lambda e: e["match"])
    prev, now = ctx["prev_now"], ctx["now"]
    frozen = ctx.get("frozen", {})
    champion_b = ctx.get("champion_b", {})

    # Delta vs previous edition (the "news" of this edition)
    deltas_vs_prev = []
    for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
        if t in prev:
            d = 100 * (now[t]["champion"] - prev[t]["champion"])
            if abs(d) >= 0.05:
                deltas_vs_prev.append(f"{t} {d:+.1f}")
    delta_line = ("; ".join(deltas_vs_prev) if deltas_vs_prev
                  else "no contender moved by 0.1 pp or more")

    # Track A vs Frozen: cumulative shift from baseline
    deltas_af = []
    for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
        if t in frozen:
            d = 100 * (now[t]["champion"] - frozen[t].get("champion", 0.0))
            if abs(d) >= 0.05:
                deltas_af.append(f"{t} {d:+.1f}")
    delta_af = ("; ".join(deltas_af) if deltas_af
                else "no contender has moved 0.1 pp or more from baseline")

    # Track B vs Track A: gap between the two tracks
    b_vs_a_line = ""
    if champion_b:
        deltas_ba = []
        for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
            if t in champion_b:
                d = 100 * (champion_b[t] - now[t]["champion"])
                if abs(d) >= 0.05:
                    deltas_ba.append(f"{t} {d:+.1f}")
        delta_ba = ("; ".join(deltas_ba) if deltas_ba
                    else "no contender diverged by 0.1 pp or more between tracks")
        b_vs_a_line = f"\\\\\nTrack~B vs.\\ Track~A: {delta_ba}."
    imp_lines = "\n".join(
        f"{i['fixture']} & {'/'.join(_pct(p) for p in i['lock_HDA'])} & "
        f"{'/'.join(_pct(p) for p in i['learn_HDA'])} \\\\"
        for i in ctx["implications"])
    imp_block = ("" if not ctx["implications"] else
        "\\paragraph{Implications for upcoming fixtures.} Frozen odds are the "
        "pre-kickoff baseline (they move only through qualification scenarios); "
        "Track~B odds incorporate live Elo and bookmaker signals.\n"
        "\\begin{footnotesize}\\begin{tabular}{lcc}\\toprule\n"
        "Fixture & Frozen H/D/A (\\%) & Track~B H/D/A (\\%) \\\\\n\\midrule\n"
        + imp_lines + "\n\\bottomrule\\end{tabular}\\end{footnotesize}\n")
    return (
        f"\\subsection{{Revision report: edition M{m:03d}}}\\label{{sec:revreport}}\n"
        f"\\paragraph{{The data release.}} Match {latest['match']}, "
        f"{latest['fixture']}: predicted {latest['pre']['pick'][0]}--"
        f"{latest['pre']['pick'][1]}, actual {latest['result'][0]}--"
        f"{latest['result'][1]}; {latest['post']['points']} of 3 points, Brier "
        f"{latest['post']['brier']:.3f}, {latest['post']['info_bits']:.3f} bits.\n\n"
        + _cumulative_stats_table(
            ctx["entries"], ctx["match_stats"],
            ctx.get("expectations", [])) + "\n\n"
        f"\\paragraph{{Forecast revision (vs.\\ edition M{ctx['vintages_rows'][-2]['edition']:03d}).}} "
        f"Champion-probability movement (vs.\\ previous edition): {delta_line}.\\\\\n"
        f"Track~A vs.\\ Frozen: {delta_af}.{b_vs_a_line}\n\n"
        + imp_block +
        "\\paragraph{Forecast vintages.} One column per issued edition; the "
        "locked M000 column never changes.\n\n"
        + vin.latex_table(ctx["vintages_rows"]))


# ---- new units (design spec 2026-06-13) ----

def abstract_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_abstract_live(ctx, use_api)
    return text


def intro_data_note_unit(ctx, use_api=False):
    text, _ = _ds.draft_intro_data_note(ctx, use_api)
    return text


def simulation_note_unit(ctx, use_api=False):
    text, _ = _ds.draft_simulation_note(ctx, use_api)
    return text


def data_revealed_unit(ctx, use_api=False):
    text, _ = _ds.draft_data_revealed(ctx, use_api)
    validate_labels("data_revealed", text, ["tab:live_data_revealed"])
    return text


def sec36_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_sec36_live(ctx, use_api)
    return text


def robustness_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_robustness_live(ctx, use_api)
    validate_labels("robustness_live", text, ["sec:live_robust"])
    return text


def failure_analysis_unit(ctx, use_api=False):
    text, _ = _ds.draft_failure_analysis(ctx, use_api)
    validate_labels("failure_analysis", text, ["sec:live_failure"])
    return text


def discussion_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_discussion_live(ctx, use_api)
    return text


def champdist_live_unit(ctx):
    """Figure block: live champion probability distribution."""
    return (
        "\\begin{figure}[!t]\n"
        "  \\caption{Champion probability distribution, conditioned on "
        "\\liveDocumented{} results (live edition M\\liveEditionNum{})}"
        "\\label{fig:live_champdist}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_champdist.pdf}\\par}\n"
        "  \\small\\textit{Note:} The frozen baseline (Figure~\\ref{fig:champdist}) "
        "is unchanged; this figure conditions on all played results.\n"
        "\\end{figure}"
    )


def groupqual_live_unit(ctx):
    """Two figure blocks: Track A and Track B qualification probabilities."""
    return (
        "\\begin{figure}[!t]\n"
        "  \\caption{Qualification probability by team --- Track~A "
        "(conditioned on \\liveDocumented{} results, June~10 ratings frozen; "
        "live edition M\\liveEditionNum{})}\\label{fig:live_groupqual}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_groupqual.pdf}\\par}\n"
        "\\end{figure}\n\n"
        "\\begin{figure}[!t]\n"
        "  \\caption{Qualification probability by team --- Track~B "
        "(result-conditioning + live Elo + bookmaker odds; "
        "live edition M\\liveEditionNum{})}\\label{fig:live_groupqual_b}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_groupqual_b.pdf}\\par}\n"
        "\\end{figure}"
    )


def bracket_live_unit(ctx):
    """Knockout bracket: placeholder during group stage, live figure once KO begins."""
    ko_results = ctx.get("results", {}).get("ko", {})
    if not ko_results:
        return (
            "\\textit{No knockout results yet; the frozen bracket "
            "(Figure~\\ref{fig:bracket}) remains the current best estimate.}"
        )
    return (
        "\\begin{figure}[!t]\n"
        "  \\caption{The submitted bracket updated through M\\liveEditionNum{}; "
        "shaded cells are confirmed results}\\label{fig:live_bracket}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_bracket.pdf}\\par}\n"
        "\\end{figure}"
    )


def survival_colcomp_unit(ctx):
    """Appendix B.live: side-by-side Frozen / Track A / Track B survival probabilities.
    Shows F/A/B when ctx['now_b'] is available, F/A otherwise."""
    frozen = ctx["frozen"]
    now = ctx["now"]
    now_b = ctx.get("now_b", {})
    has_b = bool(now_b)
    teams = sorted(now, key=lambda t: (-now[t]["champion"], -now[t]["advance_KO"]))
    stages = ["advance_KO", "R16", "QF", "SF", "final", "champion"]
    headers = "Team & KO & R16 & QF & SF & Final & Champion \\\\"

    def triple(t, stage):
        f = frozen.get(t, {}).get(stage, 0.0)
        a = now[t].get(stage, 0.0)
        delta = abs(a - f)
        a_str = f"\\textbf{{{_pct(a)}}}" if delta > 3.0 else _pct(a)
        if has_b and t in now_b:
            b = now_b[t].get(stage, 0.0)
            return f"{_pct(f)}/{a_str}/{_pct(b)}"
        return f"{_pct(f)}/{a_str}"

    rows = [
        t + " & " + " & ".join(triple(t, s) for s in stages) + " \\\\"
        for t in teams if t in frozen
    ]
    if has_b:
        note = "Each cell shows F/A/B = Frozen\\%{}/Track~A\\%/Track~B\\%; bold Track~A when $|\\Delta| > 3$ pp."
        title = "Frozen / Track~A / Track~B stage probabilities, all 48 teams"
    else:
        note = "Each cell shows Frozen\\%{}~/{}Track~A\\%; bold Track~A when $|\\Delta| > 3$ pp."
        title = "Frozen vs.\\ Track~A stage probabilities, all 48 teams"
    return (
        "\\section*{Appendix B.live\\quad The same distribution, "
        "all three tracks side by side}\\label{app:survlive}\n"
        + note + "\n\n"
        "\\begin{footnotesize}\n\\begin{longtable}{lrrrrrr}\n"
        "\\caption{" + title + " "
        "(live edition M\\liveEditionNum{})}\\label{tab:live_survcomp}\\\\\n"
        "\\toprule\n" + headers + "\n\\midrule\n"
        "\\endfirsthead\n"
        "\\toprule\n" + headers + "\n\\midrule\n"
        "\\endhead\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n\\end{longtable}\n\\end{footnotesize}"
    )


def market_snap_unit(ctx):
    """§4.7 live market snapshot table + status paragraph.
    Requires ctx['market'] (dict team→prob) and ctx['champion_b'] (dict team→prob)."""
    now = ctx.get("now", {})
    frozen = ctx.get("frozen", {})
    champion_b = ctx.get("champion_b", {})
    market = ctx.get("market")
    teams = sorted(now, key=lambda t: -now[t].get("champion", 0))[:8]
    rows = []
    for t in teams:
        frz_pct = _pct(frozen.get(t, {}).get("champion", 0))
        a_pct = _pct(now[t].get("champion", 0))
        b_pct = _pct(champion_b.get(t, 0)) if champion_b else "---"
        mkt_pct = _pct(market[t]) if market and t in market else "---"
        delta = (f"{100*(now[t].get('champion', 0) - frozen.get(t, {}).get('champion', now[t].get('champion', 0))):+.1f}"
                 if t in frozen else "---")
        rows.append(f"{t} & {frz_pct} & {a_pct} & {b_pct} & {mkt_pct} & {delta} \\\\")
    table = (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Live champion-probability snapshot (live edition "
        "M\\liveEditionNum{})}\\label{tab:live_market_snap}\n"
        "\\begin{footnotesize}\\begin{tabular}{lrrrrr}\\toprule\n"
        "Team & Frozen (\\%) & Track~A (\\%) & Track~B (\\%) & "
        "Market (\\%) & $\\Delta$ (A$-$Frozen) \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\\end{footnotesize}\\end{table}"
    )
    if market:
        status = (
            "Market and Track~A rank orderings broadly agree at this edition; "
            "divergence tracking (who-moves-first) continues through knockout stages."
        )
        fig_block = (
            "\n\n"
            "\\begin{figure}[!t]\n"
            "  \\caption{Four-bar champion probability: Frozen / Track~A / Track~B / Market, "
            "top contenders (live edition M\\liveEditionNum{})}\\label{fig:live_market}\n"
            "  {\\centering\\includegraphics[width=0.94\\textwidth]"
            "{figs/fig_live_market.pdf}\\par}\n"
            "\\end{figure}"
        )
    else:
        status = "Market-probability data are not yet available for this edition."
        fig_block = ""
    return table + "\n\n" + status + fig_block


def groupqual_table_unit(ctx):
    """Table 10: Three-panel (Frozen / Track A / Track B) qualification probability,
    all teams grouped by group. Requires ctx['group_state']."""
    frozen = ctx.get("frozen", {})
    now = ctx.get("now", {})
    now_b = ctx.get("now_b", {})
    has_b = bool(now_b)
    group_state = ctx.get("group_state", [])

    if not group_state:
        return (r"\textit{Group-state not yet available; qualification table "
                r"will appear once matches are recorded.}")

    if has_b:
        col_spec = "llrrr"
        header = ("Grp & Team & Frozen (\\%) & Track~A (\\%) & Track~B (\\%) \\\\\n"
                  "\\midrule\n")
    else:
        col_spec = "llrr"
        header = "Grp & Team & Frozen (\\%) & Track~A (\\%) \\\\\n\\midrule\n"

    rows = []
    for g in group_state:
        grp = g["group"]
        teams = sorted(
            [r["team"] for r in g["rows"]],
            key=lambda t: -now.get(t, frozen.get(t, {})).get("advance_KO", 0))
        for i, t in enumerate(teams):
            grp_col = grp if i == 0 else ""
            f_pct = _pct(frozen.get(t, {}).get("advance_KO", 0))
            a_pct = _pct(now.get(t, {}).get("advance_KO", 0))
            if has_b:
                b_pct = _pct(now_b[t].get("advance_KO", 0)) if t in now_b else "---"
                rows.append(f"{grp_col} & {t} & {f_pct} & {a_pct} & {b_pct} \\\\")
            else:
                rows.append(f"{grp_col} & {t} & {f_pct} & {a_pct} \\\\")
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()

    note = ("Qual~\\% = probability of advancing to the knockout round. "
            "Frozen = pre-kickoff lock ($N$=200{,}000, never changes); "
            "Track~A = result-conditioned, June~10 ratings ($N$=50{,}000); "
            + ("Track~B = result-conditioning + live Elo + bookmaker odds ($N$=50{,}000)."
               if has_b else
               "Track~B column populated once box-score data is processed."))

    return (
        "\\begin{table}[!t]\\centering\n"
        "\\caption{Qualification probability --- Frozen / Track~A / Track~B, "
        "all teams (live edition M\\liveEditionNum{})}\\label{tab:live_groupqual_three}\n"
        "\\begin{footnotesize}\\begin{threeparttable}\n"
        f"\\begin{{tabular}}{{{col_spec}}}\\toprule\n"
        + header
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\n"
        "\\begin{tablenotes}\\notesize\n"
        f"\\item \\textit{{Notes}}: {note}\n"
        "\\end{tablenotes}\\end{threeparttable}\\end{footnotesize}\n\\end{table}"
    )


def fixture_risk_unit(ctx):
    """Table 11: Decisive upcoming fixtures — teams on the qualification bubble
    (10\\% < Track~A advance~\\% < 90\\%) with Frozen and Track~B H/D/A odds."""
    now = ctx.get("now", {})
    expectations = ctx.get("expectations", [])
    results = ctx.get("results", {})
    implications = ctx.get("implications", [])
    group_state = ctx.get("group_state", [])

    played = set(results.get("group", {}).keys())
    imp_by_fixture = {i["fixture"]: i for i in implications}

    rows = []
    for g in group_state:
        grp = g["group"]
        for e in expectations:
            if e.get("group") != grp or str(e["match"]) in played:
                continue
            home, away = e["home"], e["away"]
            h_adv = now.get(home, {}).get("advance_KO", 0)
            a_adv = now.get(away, {}).get("advance_KO", 0)
            bubble = [(t, adv) for t, adv in [(home, h_adv), (away, a_adv)]
                      if 0.10 < adv < 0.90]
            if not bubble:
                continue
            fixture = f"{home} v {away}"
            bubble_str = "; ".join(f"{t} {_pct(adv)}\\%" for t, adv in bubble)
            lock_str = "/".join(_pct(p) for p in e["probs_HDA"])
            imp = imp_by_fixture.get(fixture)
            b_hda = "/".join(_pct(p) for p in imp["learn_HDA"]) if imp else "--"
            rows.append(
                f"  {grp} & {fixture} & {bubble_str} & {lock_str} & {b_hda} \\\\"
            )

    if not rows:
        return ("\\textit{No upcoming group fixtures with bubble teams; all "
                "qualification spots are effectively decided at this stage.}")

    return (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Decisive upcoming fixtures --- bubble teams and outcome odds "
        "(live edition M\\liveEditionNum{})}\\label{tab:live_fixture_risk}\n"
        "\\begin{footnotesize}\\begin{tabular}{lllll}\\toprule\n"
        "Grp & Fixture & Bubble team(s) (Track~A Qual\\%) & "
        "Frozen H/D/A (\\%) & Track~B H/D/A (\\%) \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\\end{footnotesize}\\end{table}"
    )
