"""Render every living unit of the paper to its own generated file under
paper/live/. The skeleton WC2026_paper.tex carries only permanent \\input lines
and is never written by the pipeline; skeleton_hash + data/skeleton_sha256.txt
prove it byte-identical on every run. Pure renderers: context in, tex out."""
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import render_evolution as rev
import poisson_model as pm
import draft_sections as _ds
import iso_codes as ic

HEADER = "% GENERATED by scripts/render_live.py — do not edit by hand.\n"


def skeleton_hash(tex):
    return hashlib.sha256(tex.encode()).hexdigest()


def write_unit(live_dir, name, content):
    Path(live_dir).mkdir(parents=True, exist_ok=True)
    (Path(live_dir) / f"{name}.tex").write_text(HEADER + content + "\n",
                                                encoding="utf-8")


def validate_labels(name, content, required):
    """Raise ValueError if any required \\label{tag} is absent from content."""
    for label in required:
        if f"\\label{{{label}}}" not in content:
            raise ValueError(
                f"render_live: {name}.tex missing \\label{{{label}}} — "
                f"add it to the generator or the prompt template")


def outcome_probs(lh, la):
    """Normalized P(H/D/A) for display (poisson_model's raw triple loses the
    truncated mass beyond MAX_G goals)."""
    ph, pd, pa = pm.outcome_probs(lh, la)
    s = ph + pd + pa
    return ph / s, pd / s, pa / s


def _pct(x):
    return f"{100 * x:.1f}"


# Team -> flag markup, matching the locked group matrices in the skeleton:
# most teams use \worldflag (ISO-2), three use the preamble's custom TikZ flags.
_FLAG_ISO = {
    "Algeria": "DZ", "Argentina": "AR", "Australia": "AU", "Austria": "AT",
    "Belgium": "BE", "Bosnia and Herzegovina": "BA", "Brazil": "BR",
    "Canada": "CA", "Cape Verde": "CV", "Colombia": "CO", "Congo DR": "CD",
    "Croatia": "HR", "Czechia": "CZ", "Ecuador": "EC", "Egypt": "EG",
    "France": "FR", "Germany": "DE", "Ghana": "GH", "Haiti": "HT", "Iran": "IR",
    "Iraq": "IQ", "Ivory Coast": "CI", "Japan": "JP", "Jordan": "JO",
    "Mexico": "MX", "Morocco": "MA", "Netherlands": "NL", "New Zealand": "NZ",
    "Norway": "NO", "Panama": "PA", "Paraguay": "PY", "Portugal": "PT",
    "Qatar": "QA", "Saudi Arabia": "SA", "Senegal": "SN", "South Africa": "ZA",
    "South Korea": "KR", "Spain": "ES", "Sweden": "SE", "Switzerland": "CH",
    "Tunisia": "TN", "Turkey": "TR", "United States": "US", "Uruguay": "UY",
    "Uzbekistan": "UZ",
}
_FLAG_CUSTOM = {"England": "\\flagENG", "Scotland": "\\flagSCO", "Curaçao": "\\flagCUW"}

# Three-letter FIFA codes — compact, fixed-width team labels so every group
# table is the same width regardless of how long the team names are.
_CODE3 = {
    "Mexico": "MEX", "South Korea": "KOR", "Czechia": "CZE", "South Africa": "RSA",
    "Switzerland": "SUI", "Canada": "CAN", "Bosnia and Herzegovina": "BIH",
    "Qatar": "QAT", "Brazil": "BRA", "Morocco": "MAR", "Scotland": "SCO",
    "Haiti": "HAI", "United States": "USA", "Turkey": "TUR", "Paraguay": "PAR",
    "Australia": "AUS", "Germany": "GER", "Ecuador": "ECU", "Ivory Coast": "CIV",
    "Curaçao": "CUW", "Netherlands": "NED", "Japan": "JPN", "Sweden": "SWE",
    "Tunisia": "TUN", "Belgium": "BEL", "Egypt": "EGY", "Iran": "IRN",
    "New Zealand": "NZL", "Spain": "ESP", "Uruguay": "URU", "Cape Verde": "CPV",
    "Saudi Arabia": "KSA", "France": "FRA", "Norway": "NOR", "Senegal": "SEN",
    "Iraq": "IRQ", "Argentina": "ARG", "Austria": "AUT", "Algeria": "ALG",
    "Jordan": "JOR", "Portugal": "POR", "Colombia": "COL", "Uzbekistan": "UZB",
    "Congo DR": "COD", "England": "ENG", "Croatia": "CRO", "Panama": "PAN",
    "Ghana": "GHA",
}


def _code3(team):
    return _CODE3.get(team, team[:3].upper())


def _flag(team):
    """Mini flag for a team, sized to match the locked group matrices (4mm×2.7mm)."""
    if team in _FLAG_CUSTOM:
        return f"\\resizebox{{4mm}}{{2.7mm}}{{{_FLAG_CUSTOM[team]}[10mm]}}"
    iso = _FLAG_ISO.get(team)
    if iso:
        return f"\\resizebox{{4mm}}{{2.7mm}}{{\\worldflag[width=10mm]{{{iso}}}}}"
    return ""


# ---- ported units (reuse render_evolution's pure builders) ----

def ledger(entries, upcoming=None, issue_order=None):
    return rev.ledger_table(entries, upcoming=upcoming, issue_order=issue_order)


def narrative_unit(entries):
    return rev.narrative(entries)


def trajfig_unit(entries, live_fig):
    return rev.trajfig(entries, live_fig)


def champ_table_unit(frozen, now, n_results, champion_b=None, market=None):
    return rev.champ_table(frozen, now, n_results, champion_b=champion_b,
                           market=market)


def divergence_unit(frozen, now, entries, group_state, champion_b=None,
                    now_b=None, drift=None):
    played = [g for g in group_state if g["played"]]
    return rev.divergence_section(frozen, now, entries, played,
                                  champion_b=champion_b, now_b=now_b, drift=drift)


# ---- new units ----

def tracker(group_state, frozen, now):
    """Main-text 'state of the group stage': one row per group. frozen is
    accepted for signature symmetry with the other units; the table shows
    only current values."""
    rows = []
    for g in group_state:
        top2 = g["rows"][:2]
        if g["played"]:
            standing = "; ".join(f"{r['team']} {r['Pts']}" for r in top2)
        else:
            standing = "--"
        leaders = sorted((r for r in g["rows"] if r["team"] in now),
                         key=lambda r: -now[r["team"]]["advance_KO"])[:2]
        qual = "; ".join(
            f"{r['team']} {_pct(now[r['team']]['advance_KO'])}" for r in leaders)
        rows.append(f"{g['group']} & {g['played']}/{g['total']} & {standing} & {qual} \\\\")
    return (
        "\\begin{table}[!t]\n  \\centering\n"
        "  \\caption{State of the group stage (live edition)}\\label{tab:tracker}\n"
        "  \\begin{footnotesize}\n"
        "  {\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} clll}\n"
        "    \\toprule\n"
        "    Group & Played & Standings (top two, real points) & Advance now (top two) \\\\\n"
        "    \\midrule\n    " + "\n    ".join(rows) + "\n"
        "    \\bottomrule\n  \\end{tabular*}}\n  \\end{footnotesize}\n\\end{table}")


def _record_from(team, group_exps, res_by_match, resolver):
    """Tally (W, D, L, Pts) for `team` across its group fixtures, taking played
    matches from `res_by_match` and unplayed ones from resolver(e) -> (hg, ag)."""
    w = d = l = pts = 0
    for e in group_exps:
        if team not in (e["home"], e["away"]):
            continue
        res = res_by_match.get(str(e["match"]))
        hg, ag = (tuple(res) if res else resolver(e))
        tf, ta = (hg, ag) if e["home"] == team else (ag, hg)
        if tf > ta:
            w += 1; pts += 3
        elif tf == ta:
            d += 1; pts += 1
        else:
            l += 1
    return w, d, l, pts


def group_box(g_state, results, expectations, frozen, now, now_b=None, track_b=None):
    """Appendix-A unified group table (spec 3.15) — ONE table per group, in the
    locked-matrix style: flag column headers (no rotated names), flag+name row
    labels, and a round-robin body whose played cells carry the bold actual score
    + check/cross and whose upcoming cells carry the predicted scoreline under
    Frozen/Track~A (one line, since both ride the June-10 ratings) and Track~B.
    Right panels give the Actual record (W/D/L/Pts/Qual\\%) and the projected
    final W/D/L/Pts under Frozen/Track~A and under Track~B. A remaining-fixtures
    H/D/A block sits below. track_b: {match: {'pick':[h,a],'hda':[h,d,a]}}."""
    grp = g_state["group"]
    teams = [r["team"] for r in g_state["rows"]]
    group_exps = [e for e in expectations if e.get("group") == grp]
    exps = {(e["home"], e["away"]): e for e in group_exps}
    res_by_match = results["group"]
    track_b = track_b or {}

    if not group_exps:
        return f"\\paragraph{{Group {grp} — live.}} Fixtures pending."

    def _sgn(x): return 1 if x > 0 else (-1 if x < 0 else 0)

    def _frozen_pick(e):                # Frozen and Track A share the submitted pick
        return tuple(e["pick"])

    def _track_b_pick(e):
        return tuple(track_b.get(e["match"], {}).get("pick", e["pick"]))

    # ---- one round-robin table, locked-matrix style -------------------------
    n = len(teams)
    col_spec = "cl" + "c" * n + "cccc"
    flag_hdr = " & ".join(_flag(t) for t in teams)
    panel_hdr = (
        "\\makecell{Actual \\\\ W/D/L/P} & "
        "\\makecell{Frozen \\\\ W/D/L/P/Q\\%} & "
        "\\makecell{Track~A \\\\ W/D/L/P/Q\\%} & "
        "\\makecell{Track~B \\\\ W/D/L/P/Q\\%}")
    header = f" & Team & {flag_hdr} & {panel_hdr} \\\\"

    body_rows = []
    for rank, home in enumerate(teams, 1):
        cells = []
        for away in teams:
            if home == away:
                cells.append("---")
                continue
            e = exps.get((home, away)) or exps.get((away, home))
            if e is None:
                cells.append("?")
                continue
            res = res_by_match.get(str(e["match"]))
            if res:                      # played: bold actual score + correct mark
                score = (f"{res[0]}--{res[1]}" if e["home"] == home
                         else f"{res[1]}--{res[0]}")
                pick = e["pick"]
                correct = _sgn(pick[0] - pick[1]) == _sgn(res[0] - res[1])
                icon = r"$\checkmark$" if correct else r"$\times$"
                cells.append(f"\\textbf{{{score}}}{icon}")
            else:                        # upcoming: Frozen=Track~A scoreline; Track~B if it differs
                fa, tb = _frozen_pick(e), _track_b_pick(e)
                if e["home"] == home:
                    f_s, b_s = f"{fa[0]}--{fa[1]}", f"{tb[0]}--{tb[1]}"
                else:
                    f_s, b_s = f"{fa[1]}--{fa[0]}", f"{tb[1]}--{tb[0]}"
                cells.append(f"F/A/B:{f_s}" if f_s == b_s
                             else f"F/A:{f_s}\\, B:{b_s}")

        # right panels — each W/D/L/Pts/Qual%: Actual (real record + current
        # qual), then projected final record under Frozen / Track A / Track B.
        # Records coincide for Frozen and Track A (shared June-10 ratings); the
        # qualification probabilities differ because Track A is result-conditioned.
        row = next((r for r in g_state["rows"] if r["team"] == home), {})
        aw, ad, al = row.get("W", 0), row.get("D", 0), row.get("L", 0)
        apts = row.get("Pts", 0)
        q_frozen = _pct(frozen[home]["advance_KO"]) if home in frozen else "--"
        q_a = _pct(now[home]["advance_KO"]) if home in now else "--"
        q_b = _pct(now_b[home]["advance_KO"]) if (now_b and home in now_b) else "--"
        actual = f"{aw}/{ad}/{al}/{apts}" if g_state["played"] else "--"
        fw, fd, fl, fp = _record_from(home, group_exps, res_by_match, _frozen_pick)
        bw, bd, bl, bp = _record_from(home, group_exps, res_by_match, _track_b_pick)
        body_rows.append(
            f"{rank} & {_flag(home)}~{_code3(home)} & " + " & ".join(cells)
            + f" & {actual} & {fw}/{fd}/{fl}/{fp}/{q_frozen}\\%"
            f" & {fw}/{fd}/{fl}/{fp}/{q_a}\\% & {bw}/{bd}/{bl}/{bp}/{q_b}\\% \\\\"
        )

    # ---- remaining-fixtures H/D/A block (below the matrix) -------------------
    state = (f"{g_state['played']} of {g_state['total']} played"
             if g_state["played"] else "fixtures pending")
    note = ("Teams are 3-letter codes. Round-robin body: row team's score against "
            "the column team. Played cells show the actual score in bold with "
            "$\\checkmark$/$\\times$ for the submitted result pick; upcoming cells "
            "give the predicted scoreline as F/A (Frozen=Track~A) and B (Track~B), "
            "collapsed to F/A/B when all agree. Right panels report W/D/L/Pts and "
            "qualification \\%: Actual is the real record so far; Frozen, Track~A, "
            "and Track~B give the projected final record (each remaining game "
            "resolved at that track's predicted scoreline) and that track's qual. "
            "Frozen and Track~A share the June~10 ratings, so their scoreline and "
            "projected record coincide; the two diverge only in the conditioned "
            "qualification \\%.")

    return (
        f"\\paragraph{{Group {grp} — live ({state}).}}\\leavevmode\\par\n"
        "\\noindent\\begin{threeparttable}\n"
        "{\\setlength{\\tabcolsep}{3pt}\\scriptsize\n"
        f"\\begin{{tabular*}}{{\\textwidth}}{{@{{\\extracolsep{{\\fill}}}}{col_spec}@{{}}}}\n"
        "\\toprule\n"
        f"{header}\n"
        "\\midrule\n"
        + "\n".join(body_rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular*}}\n"
        "\\begin{tablenotes}\\notesize\n"
        f"\\item \\textit{{Notes}}: {note}\n"
        "\\end{tablenotes}\n\\end{threeparttable}\n"
    )


def two_track_unit(two_track, learning, fig=False, info_snapshot=None, track_a=None,
                   champion_b=None, frozen_stages=None):
    """The live A-vs-B narrative. The champion-odds table is a strict subset of
    the headline Table~\\ref{tab:champ} (dropped); the learning-track Elo drift
    is folded into the divergence table (Table~\\ref{tab:live_divergence}); and
    the realized champion paths are the trajectory, Figure~\\ref{fig:trajectory}
    (the former standalone two-track path figure was redundant with it). fig /
    track_a / champion_b / frozen_stages / info_snapshot are accepted for caller
    compatibility but no longer rendered here."""
    if two_track is None:
        return ("\\textit{Two-track live results begin with the first match "
                "whose box score is collected.}")
    pend = (f" Stats pending for matches: "
            f"{', '.join(f'M{m:03d}' for m in learning['pending'])}."
            if learning["pending"] else "")
    n = len(learning["processed"])

    return (
        "\\subsection{The two tracks live: 2026 as it speaks}"
          "\\label{sec:twotracklive}\n"
          f"The pre-registered A-vs-B study of Appendix~D, running on the real "
          f"tournament: after each match the observed shot performance "
          f"($\\lambda_{{\\mathrm{{obs}}}}$, Appendix~D.2) updates Track~B's "
          f"ratings (k=50, locked), while Track~A re-conditions "
          f"on results alone. {n} match(es) processed so far.{pend}\n\n"
          "The three champion tracks are tabulated in "
          "Table~\\ref{tab:champ} (Frozen / Track~A / Track~B / Market) and their "
          "realized paths are Figure~\\ref{fig:trajectory}; the learning-track "
          "Elo drift that distinguishes Track~B is folded into the divergence "
          "table, Table~\\ref{tab:live_divergence}.")


def _stats_release(match, match_stats, learning):
    s = match_stats.get(match)
    rec = next((r for r in learning["processed"] if r["match"] == match), None)
    if s is None:
        return ("\\textit{Box-score statistics for this match are pending; the "
                "performance analysis will appear in the next edition.}")
    def _row(label, key, fmt="{:.0f}"):
        return (f"{label} & " + fmt.format(s['home'][key]) + " & "
                + fmt.format(s['away'][key]) + " \\\\")
    lines = [_row("Shots", "total_shots"), _row("On target", "sot")]
    if (s["home"].get("possession") is not None
            and s["away"].get("possession") is not None):
        lines.append(_row("Possession (\\%)", "possession", "{:.0f}"))
    perf = ""
    if rec:
        perf = (f"\\\\[2pt] Performance vs.\\ expectation: "
                f"$\\lambda_{{\\mathrm{{obs}}}}$ = {rec['lam_obs']['home']:.2f} / "
                f"{rec['lam_obs']['away']:.2f} against "
                f"$\\lambda_{{\\mathrm{{exp}}}}$ = {rec['lam_exp']['home']:.2f} / "
                f"{rec['lam_exp']['away']:.2f} "
                f"({rec['lam_obs']['source']} signal); the learning track moves "
                f"{rec['home']} by {rec['drift_after'].get(rec['home'], 0):+.1f} and "
                f"{rec['away']} by {rec['drift_after'].get(rec['away'], 0):+.1f} Elo.")
    return ("\\begin{table}[!h]\\centering\n"
            "\\caption{Match statistics (live edition M\\liveEditionNum{})}\\label{tab:live_edition_snapshot}\n"
            "\\begin{footnotesize}\\begin{tabular}{lrr}\\toprule\n"
            f" & {s['home']['team']} & {s['away']['team']} \\\\\n\\midrule\n"
            + "\n".join(lines) + "\n\\bottomrule\\end{tabular}\\end{footnotesize}"
            + perf
            + "\n\\end{table}")


def _pad2(v):
    """Two-digit zero-padded integer for column alignment (7 -> 07, 16 -> 16).
    Shots and shots-on-target are whole counts. '--' passes through unchanged."""
    return f"{int(round(v)):02d}" if isinstance(v, (int, float)) else str(v)


def _ppct(x):
    """Zero-padded percent, integer part to two digits (0.061 -> 06.1, 0.672 ->
    67.2), so the H/D/A triples line up under one another."""
    return f"{100 * x:04.1f}"


def _cumulative_stats_table(entries, match_stats, expectations, issue_order=None,
                            implications=None):
    """Table 7: a two-panel table. Panel A is one row per played match, grows
    with each edition, ordered by true issue order (GXXX, the order the model
    conditioned on results) not by schedule number (MXXX); the Game column shows
    both. Panel B (when ``implications`` is given) folds in the upcoming-fixture
    implications that used to be a separate unnumbered table.
    Panel A columns: Game | Shots H–A | On target H–A | Poss H–A | Frozen H/D/A |
    Track B H/D/A. Track B H/D/A is stored in entry['pre']['probs_HDA_b'] at
    documentation time (pre-match learn_ratings); '--' before that feature."""
    rows = []
    exp_by_match = {e["match"]: e for e in expectations}
    if issue_order:
        gidx = {m: i + 1 for i, m in enumerate(issue_order)}   # 1-based G index
        ordered = sorted(entries, key=lambda e: gidx.get(e["match"], 10 ** 6))
    else:
        gidx = {}
        ordered = list(entries)
    for pos, e in enumerate(ordered, start=1):
        m = e["match"]
        s = match_stats.get(m)
        if s is None:
            continue
        g = gidx.get(m, pos)            # true issue position (matches Table 8)
        sh = _pad2(s["home"].get("total_shots", "--"))
        sa = _pad2(s["away"].get("total_shots", "--"))
        oh = _pad2(s["home"].get("sot", "--"))
        oa = _pad2(s["away"].get("sot", "--"))
        ph = s["home"].get("possession")
        pa = s["away"].get("possession")
        poss = f"{ph:02.0f}--{pa:02.0f}" if ph is not None and pa is not None else "--"
        exp = exp_by_match.get(m)
        hda = "/".join(_ppct(p) for p in exp["probs_HDA"]) if exp else "--"
        hda_b_raw = e.get("pre", {}).get("probs_HDA_b")
        hda_b = "/".join(_ppct(p) for p in hda_b_raw) if hda_b_raw else "--"
        rows.append(
            f"{g} & {m} & {ic.fixture_tag(e['fixture'])} & {sh}--{sa} & "
            f"{oh}--{oa} & {poss} & {hda} & {hda_b} \\\\")
    if not rows and not implications:
        return r"\textit{Match statistics pending.}"
    # One aligned tabular so Panel B's last two columns line up beneath Panel A's,
    # with shared G / M columns. Columns: G | M | Fixture | Shots | On target |
    # Poss% | Frozen H/D/A | Track B H/D/A.
    col_spec = "rrlccccc"
    header = ("G & M & Fixture & Shots (H--A) & On target (H--A) & "
              "Poss\\% (H--A) & Frozen H/D/A & Track~B H/D/A \\\\")
    body = ["\\multicolumn{8}{@{}l}{\\itshape Panel A. Cumulative match statistics "
            "(played matches, in issue order).} \\\\", "\\midrule", header, "\\midrule"]
    body += rows if rows else [
        "\\multicolumn{8}{@{}l}{\\itshape Match statistics pending.} \\\\"]
    if implications:
        body += ["\\midrule",
                 "\\multicolumn{8}{@{}l}{\\itshape Panel B. Implications for upcoming "
                 "fixtures --- Frozen = pre-kickoff baseline; Track~B = live Elo + "
                 "bookmaker odds.} \\\\", "\\midrule"]
        for i in implications:
            body.append(
                f"-- & {i['match']} & {ic.fixture_tag(i['fixture'])} & -- & -- & -- & "
                f"{'/'.join(_ppct(p) for p in i['lock_HDA'])} & "
                f"{'/'.join(_ppct(p) for p in i['learn_HDA'])} \\\\")
    caption = ("Cumulative match statistics and upcoming-fixture implications"
               if implications else "Cumulative match statistics")
    return (
        "\\begin{table}[!h]\\centering\n"
        f"\\caption{{{caption} (live edition M\\liveEditionNum{{}})}}"
        "\\label{tab:live_match_stats}\n"
        "\\begin{footnotesize}\n"
        f"\\begin{{tabular}}{{{col_spec}}}\\toprule\n"
        + "\n".join(body) + "\n\\bottomrule\\end{tabular}\n"
        "\\end{footnotesize}\n\\end{table}"
    )


def revision_report(ctx):
    """The central-bank release: data release, forecast revision (the marginal
    effect of this match's result), implications, vintages. Driver contract:
    ctx['prev_now'] is the forecast conditioned on this edition's matches except
    the one just released, and ctx['match'] equals the latest entry's match."""
    import vintages as vin
    m = ctx["match"]
    latest = max(ctx["entries"], key=lambda e: e["match"])
    prev, now = ctx["prev_now"], ctx["now"]
    frozen = ctx.get("frozen", {})
    champion_b = ctx.get("champion_b", {})

    # Delta vs previous edition (the "news" of this edition)
    deltas_vs_prev = []
    for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
        if t in prev:
            d = 100 * (now[t]["champion"] - prev[t]["champion"])
            if abs(d) >= 0.05:
                deltas_vs_prev.append(f"{t} {d:+.1f}")
    delta_line = ("; ".join(deltas_vs_prev) if deltas_vs_prev
                  else "no contender moved by 0.1 pp or more")

    # Track A vs Frozen: cumulative shift from baseline
    deltas_af = []
    for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
        if t in frozen:
            d = 100 * (now[t]["champion"] - frozen[t].get("champion", 0.0))
            if abs(d) >= 0.05:
                deltas_af.append(f"{t} {d:+.1f}")
    delta_af = ("; ".join(deltas_af) if deltas_af
                else "no contender has moved 0.1 pp or more from baseline")

    # Track B vs Track A: gap between the two tracks
    b_vs_a_line = ""
    if champion_b:
        deltas_ba = []
        for t in sorted(now, key=lambda t: -now[t]["champion"])[:8]:
            if t in champion_b:
                d = 100 * (champion_b[t] - now[t]["champion"])
                if abs(d) >= 0.05:
                    deltas_ba.append(f"{t} {d:+.1f}")
        delta_ba = ("; ".join(deltas_ba) if deltas_ba
                    else "no contender diverged by 0.1 pp or more between tracks")
        b_vs_a_line = f"\n\nTrack~B vs.\\ Track~A: {delta_ba}."
    return (
        f"\\subsection{{Revision report: edition M{m:03d}}}\\label{{sec:revreport}}\n"
        f"\\paragraph{{The data release.}} Match {latest['match']}, "
        f"{latest['fixture']}: predicted {latest['pre']['pick'][0]}--"
        f"{latest['pre']['pick'][1]}, actual {latest['result'][0]}--"
        f"{latest['result'][1]}; {latest['post']['points']} of 3 points, Brier "
        f"{latest['post']['brier']:.3f}, {latest['post']['info_bits']:.3f} bits.\n\n"
        + _cumulative_stats_table(
            ctx["entries"], ctx["match_stats"],
            ctx.get("expectations", []),
            issue_order=ctx.get("issue_order"),
            implications=ctx.get("implications")) + "\n\n"
        f"\\paragraph{{Forecast revision: marginal effect of this result.}} "
        f"Champion-probability movement attributable to match {latest['match']}'s "
        f"result (this edition vs.\\ the same forecast without it): {delta_line}.\n\n"
        f"Track~A vs.\\ Frozen: {delta_af}.{b_vs_a_line}\n\n"
        "\\paragraph{Forecast vintages.} Track~B champion probabilities, one row "
        "per issued edition, in issue order; the locked M000 (Frozen baseline) "
        "row never changes.\n\n"
        + vin.latex_table(ctx["vintages_rows"], issue_order=ctx.get("issue_order")))


# ---- new units (design spec 2026-06-13) ----

def abstract_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_abstract_live(ctx, use_api)
    return text


def intro_data_note_unit(ctx, use_api=False):
    text, _ = _ds.draft_intro_data_note(ctx, use_api)
    return text


def simulation_note_unit(ctx, use_api=False):
    text, _ = _ds.draft_simulation_note(ctx, use_api)
    return text


def data_revealed_unit(ctx, use_api=False):
    # The per-match table moved into the ledger (Table~\ref{tab:live_ledger});
    # this section is now a pointer + Track B provenance, so no label to assert.
    text, _ = _ds.draft_data_revealed(ctx, use_api)
    return text


def sec36_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_sec36_live(ctx, use_api)
    return text


def robustness_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_robustness_live(ctx, use_api)
    validate_labels("robustness_live", text, ["sec:live_robust"])
    return text


def failure_analysis_unit(ctx, use_api=False):
    text, _ = _ds.draft_failure_analysis(ctx, use_api)
    validate_labels("failure_analysis", text, ["sec:live_failure"])
    return text


def discussion_live_unit(ctx, use_api=False):
    text, _ = _ds.draft_discussion_live(ctx, use_api)
    return text


def groupqual_live_unit(ctx):
    """Discussion + two figure blocks (Track A / Track B qualification), the
    live companions to the locked Frozen Figure~\\ref{fig:groupqual}."""
    frozen = ctx.get("frozen", {})
    now = ctx.get("now", {})
    n = ctx.get("n_results", 0)
    movers = sorted(
        ((t, frozen[t]["advance_KO"], now[t]["advance_KO"]) for t in now
         if t in frozen and "advance_KO" in now[t] and "advance_KO" in frozen[t]),
        key=lambda x: -abs(x[2] - x[1]))
    swing = ""
    if movers and abs(movers[0][2] - movers[0][1]) >= 0.005:
        t, f, a = movers[0]
        verb = "up" if a >= f else "down"
        swing = (f" The largest swing so far is {t}, {verb} from "
                 f"{_pct(f)}\\% under Frozen to {_pct(a)}\\% under Track~A.")
    discussion = (
        "\\paragraph{Qualification, three ways.} Figure~\\ref{fig:groupqual} is "
        "the pre-kickoff (Frozen) qualification decomposition --- win the group, "
        "finish second, or advance as a best third --- locked and unchanged. The "
        f"two figures below recompute it after {n} result"
        f"{'' if n == 1 else 's'}: Track~A conditions on the played outcomes with "
        "the June~10 ratings held fixed, and Track~B additionally folds in live "
        "Elo and bookmaker odds. Conditioning sharpens every group that has "
        "kicked off --- a win lifts a team's qualification mass and a defeat cuts "
        "it --- while groups still to play stay at the Frozen baseline." + swing
        + "\n\n")
    return discussion + (
        "\\begin{figure}[!t]\n"
        "  \\caption{Qualification probability by team --- Track~A "
        "(conditioned on \\liveDocumented{} results, June~10 ratings frozen; "
        "live edition M\\liveEditionNum{})}\\label{fig:live_groupqual}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_groupqual.pdf}\\par}\n"
        "\\end{figure}\n\n"
        "\\begin{figure}[!t]\n"
        "  \\caption{Qualification probability by team --- Track~B "
        "(result-conditioning + live Elo + bookmaker odds; "
        "live edition M\\liveEditionNum{})}\\label{fig:live_groupqual_b}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_groupqual_b.pdf}\\par}\n"
        "\\end{figure}"
    )


_R32_PAIRS = [
    # (home, away, match_number) — pre-registered bracket (LEFT then RIGHT half)
    ("Germany",       "Paraguay",              73),
    ("France",        "Sweden",                74),
    ("South Korea",   "Canada",                75),
    ("Netherlands",   "Morocco",               76),
    ("Colombia",      "Croatia",               77),
    ("Spain",         "Austria",               78),
    ("United States", "Bosnia and Herzegovina", 79),
    ("Belgium",       "Czechia",               80),
    ("Brazil",        "Japan",                 81),
    ("Ecuador",       "Norway",                82),
    ("Mexico",        "Ivory Coast",           83),
    ("England",       "Algeria",               84),
    ("Argentina",     "Uruguay",               85),
    ("Turkey",        "Egypt",                 86),
    ("Switzerland",   "Iran",                  87),
    ("Portugal",      "Senegal",               88),
]


def _slot_status(frozen_pct, track_b_pct):
    drop = frozen_pct - track_b_pct
    if drop < 5:
        return "\\checkmark"
    if drop <= 20:
        return "$\\triangle$"
    return "$\\times$"


def _slot_risk_table(frozen, now, now_b):
    """R32 slot-risk table: does each pre-registered pick still advance, under
    Frozen / Track A / Track B?  Group-stage companion to the bracket figures."""
    has_b = bool(now_b)
    rows = []
    for home, away, mn in _R32_PAIRS:
        for team in (home, away):
            fr = frozen.get(team, {}).get("advance_KO", 0.0)
            ta = now.get(team, frozen.get(team, {})).get("advance_KO", fr)
            tb = now_b.get(team, {}).get("advance_KO", float("nan")) if has_b else float("nan")
            fr_p, ta_p = round(100 * fr, 1), round(100 * ta, 1)
            tb_str = f"{100 * tb:.1f}" if tb == tb else "--"
            status = _slot_status(fr_p, 100 * tb if tb == tb else fr_p) if has_b else ""
            b_col = f" & {tb_str} & {status}" if has_b else ""
            rows.append(f"{team} advance & M{mn} & {fr_p} & {ta_p}{b_col} \\\\")
    if has_b:
        col_spec = "llrrrl"
        hdr = "KO Pick & Slot & Frozen~\\% & Track~A~\\% & Track~B~\\% & Status \\\\"
        note = ("Status: \\checkmark{} = Track~B within 5 pp of Frozen; "
                "$\\triangle$ = 5--20 pp drop; $\\times$ = pick reversed ($>$20 pp).")
    else:
        col_spec, hdr, note = "llrr", "KO Pick & Slot & Frozen~\\% & Track~A~\\% \\\\", ""
    notes_block = (f"\n  \\begin{{tablenotes}}\\notesize\n  \\item \\textit{{Notes:}} "
                   f"{note}\n  \\end{{tablenotes}}" if note else "")
    return (
        "\\begin{table}[!t]\n  \\centering\n"
        "  \\caption{R32 slot risk: probability each pre-registered pick "
        "advances from the group stage (live edition M\\liveEditionNum{})"
        "}\\label{tab:live_slot_risk}\n"
        f"  \\begin{{footnotesize}}\\begin{{threeparttable}}\n"
        f"  \\begin{{tabular}}{{{col_spec}}}\n"
        f"  \\toprule\n  {hdr}\n  \\midrule\n  " + "\n  ".join(rows) + "\n"
        "  \\bottomrule\\end{tabular}"
        + notes_block +
        "\n  \\end{threeparttable}\\end{footnotesize}\n\\end{table}")


def bracket_live_unit(ctx):
    """The knockout bracket, three ways (spec 3.20): the submitted Frozen bracket
    is the locked TikZ Figure~\\ref{fig:bracket}; the live Track A and Track B
    brackets re-value that same bracket by champion probability and grey out
    teams eliminated by confirmed results. During the group stage a slot-risk
    table also tracks whether each R32 pick is still advancing."""
    ko_results = ctx.get("results", {}).get("ko", {})
    frozen, now = ctx.get("frozen", {}), ctx.get("now", {})
    now_b = ctx.get("now_b", {})

    discussion = (
        "\\paragraph{The bracket, three ways.} The submitted knockout entry is "
        "the Frozen bracket of Figure~\\ref{fig:bracket}, which never changes. "
        "The two live brackets below re-value that same submitted bracket by each "
        "team's champion probability under Track~A (result-conditioning on the "
        "June~10 ratings) and Track~B (live Elo and bookmaker odds), and once the "
        "knockout rounds begin they shade out teams eliminated by confirmed "
        "results. Read together with the locked bracket, they show how far the "
        "live forecast has drifted from the path the entry committed to; the "
        "slot-risk table below tracks the same question one pick at a time while "
        "the group stage is still running.\n\n")

    slot_table = ("" if ko_results
                  else _slot_risk_table(frozen, now, now_b) + "\n\n")

    figs = (
        "\\begin{figure}[!t]\n"
        "  \\caption{The submitted bracket re-valued by champion probability "
        "under Track~A (top) and Track~B (bottom) at live edition "
        "M\\liveEditionNum{}; the gold box is each track's most likely champion "
        "and greyed boxes are teams eliminated by confirmed results. The locked "
        "submitted bracket is Figure~\\ref{fig:bracket}.}\\label{fig:live_bracket}\n"
        "  {\\centering\\includegraphics[width=0.92\\textwidth]"
        "{figs/fig_live_bracket_a.pdf}\\par\\smallskip\n"
        "  \\includegraphics[width=0.92\\textwidth]"
        "{figs/fig_live_bracket_b.pdf}\\par}\n"
        "\\end{figure}")

    ml_figs = (
        "\\begin{figure}[!t]\n"
        "  \\caption{The \\emph{most-likely} bracket: the same submitted layout, "
        "but each Round-of-32 slot is re-filled with the team most likely to "
        "occupy it (rather than the locked pick) under Track~A (top) and Track~B "
        "(bottom) at live edition M\\liveEditionNum{}. Round-of-32 boxes show the "
        "probability that team reaches the slot; rounds past the Round of 32 trace "
        "the Elo most-likely path with boxes showing champion probability, and "
        "upgrade to exact per-slot occupancy once the knockout draw is realised. "
        "Read against Figure~\\ref{fig:live_bracket}, it shows where the live "
        "forecast would re-cast the bracket the entry locked in.}"
        "\\label{fig:mostlikely_bracket}\n"
        "  {\\centering\\includegraphics[width=0.92\\textwidth]"
        "{figs/fig_mostlikely_bracket_a.pdf}\\par\\smallskip\n"
        "  \\includegraphics[width=0.92\\textwidth]"
        "{figs/fig_mostlikely_bracket_b.pdf}\\par}\n"
        "\\end{figure}")

    return discussion + slot_table + figs + "\n\n" + ml_figs


def survival_colcomp_unit(ctx):
    """Appendix B.live: side-by-side Frozen / Track A / Track B survival probabilities.
    Shows F/A/B when ctx['now_b'] is available, F/A otherwise."""
    frozen = ctx["frozen"]
    now = ctx["now"]
    now_b = ctx.get("now_b", {})
    has_b = bool(now_b)
    teams = sorted(now, key=lambda t: (-now[t]["champion"], -now[t]["advance_KO"]))
    stages = ["advance_KO", "R16", "QF", "SF", "final", "champion"]
    headers = "Team & KO & R16 & QF & SF & Final & Champion \\\\"

    def triple(t, stage):
        f = frozen.get(t, {}).get(stage, 0.0)
        a = now[t].get(stage, 0.0)
        delta = abs(a - f)            # zero-padded (07.0) so the F/A/B cells align
        a_str = f"\\textbf{{{_ppct(a)}}}" if delta > 3.0 else _ppct(a)
        if has_b and t in now_b:
            b = now_b[t].get(stage, 0.0)
            return f"{_ppct(f)}/{a_str}/{_ppct(b)}"
        return f"{_ppct(f)}/{a_str}"

    rows = [
        t + " & " + " & ".join(triple(t, s) for s in stages) + " \\\\"
        for t in teams if t in frozen
    ]
    if has_b:
        note = "Each cell shows F/A/B = Frozen\\%{}/Track~A\\%/Track~B\\%; bold Track~A when $|\\Delta| > 3$ pp."
        title = "Frozen / Track~A / Track~B stage probabilities, all 48 teams"
    else:
        note = "Each cell shows Frozen\\%{}~/{}Track~A\\%; bold Track~A when $|\\Delta| > 3$ pp."
        title = "Frozen vs.\\ Track~A stage probabilities, all 48 teams"
    return (
        "\\section*{Appendix B\\quad The same distribution, "
        "all three tracks side by side}\\label{app:survlive}\n"
        + note + "\n\n"
        "\\begin{scriptsize}\n\\begin{longtable}{lrrrrrr}\n"
        "\\caption{" + title + " "
        "(live edition M\\liveEditionNum{})}\\label{tab:live_survcomp}\\\\\n"
        "\\toprule\n" + headers + "\n\\midrule\n"
        "\\endfirsthead\n"
        "\\toprule\n" + headers + "\n\\midrule\n"
        "\\endhead\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n\\end{longtable}\n\\end{scriptsize}"
    )


def market_snap_unit(ctx):
    """§4.7 live model-vs-market status paragraph + the consolidated champion
    figure. The former champion-probability snapshot table is removed: its
    Frozen/Track~A/Track~B/Market/Δ columns are folded into the headline
    Table~\\ref{tab:champ} (champ_table), so only the figure carries the market
    here. Requires ctx['market'] and ctx['champion_b']."""
    market = ctx.get("market")
    if market:
        status = (
            "Market and Track~A rank orderings broadly agree at this edition; "
            "divergence tracking (who-moves-first) continues through knockout stages."
        )
        market_note = (
            "\\emph{Market} is the live Polymarket champion distribution, "
            "normalized to remove the overround. "
        )
    else:
        status = "Market-probability data are not yet available for this edition."
        market_note = (
            "\\emph{Market} bars are omitted until Polymarket data are available "
            "for this edition. "
        )
    # The figure (and its label) is emitted in every edition so the baseline
    # references to Figure~\\ref{fig:live_market} always resolve, even before any
    # market data arrive.
    fig_block = (
        "\n\n"
        "\\begin{figure}[!t]\n"
        "  \\caption{Champion probability, four ways: Frozen / Track~A / "
        "Track~B / Market, top twelve teams "
        "(live edition M\\liveEditionNum{})}\\label{fig:live_market}\n"
        "  {\\centering\\includegraphics[width=0.94\\textwidth]"
        "{figs/fig_live_market.pdf}\\par}\n"
        "  \\small\\textit{Note:} The single champion-probability instrument "
        "for the live edition. \\emph{Frozen} is the locked pre-kickoff "
        "200{,}000-simulation baseline (unchanged all tournament, the modal "
        "champion still fails to win most simulations); \\emph{Track~A} and "
        "\\emph{Track~B} condition on the results revealed so far; "
        + market_note +
        "Bars are ordered by Track~A; the 200k baseline keeps roughly a tenth "
        "of its mass outside the twelve named teams.\n"
        "\\end{figure}"
    )
    return status + fig_block


def _abbrev_team(t, n=14):
    """Match the locked Table 13 abbreviation style (e.g. 'Bosnia and He.')."""
    return t if len(t) <= n else t[:n - 1].rstrip() + "."


def _finish_cells(d):
    """Three finishing-position cells + Qual as integer percents from a stage
    dict carrying first/second/third_adv/advance_KO, or four '--' when absent."""
    if not d:
        return ["--", "--", "--", "--"]
    return [f"{100 * d.get('first', 0):.0f}",
            f"{100 * d.get('second', 0):.0f}",
            f"{100 * d.get('third_adv', 0):.0f}",
            f"\\textbf{{{100 * d.get('advance_KO', 0):.0f}}}"]


def groupqual_table_unit(ctx):
    """Table 10: three-panel finishing-position table (Frozen / Track A / Track B),
    14 columns: Grp, Team, then 1st/2nd/3rd*/Qual for each track. Frozen panel is
    the locked Table 13 (ctx['frozen_finish'], 100k sims); Track A/B carry the
    finishing-position keys added by condition.conditional_probs."""
    frozen_finish = ctx.get("frozen_finish", {})   # {grp: {team: {p1,p2,p3adv,qual}}}
    now = ctx.get("now", {})
    now_b = ctx.get("now_b", {})
    group_state = ctx.get("group_state", [])

    if not group_state:
        return (r"\textit{Group-state not yet available; qualification table "
                r"will appear once matches are recorded.}")

    def _frozen_cells(grp, t):
        d = frozen_finish.get(grp, {}).get(t)
        if not d:
            return ["--", "--", "--", "--"]
        return [f"{100 * d.get('p1', 0):.0f}", f"{100 * d.get('p2', 0):.0f}",
                f"{100 * d.get('p3adv', 0):.0f}",
                f"\\textbf{{{100 * d.get('qual', 0):.0f}}}"]

    rows = []
    for g in group_state:
        grp = g["group"]
        teams = sorted(
            [r["team"] for r in g["rows"]],
            key=lambda t: -now.get(t, {}).get("advance_KO",
                          frozen_finish.get(grp, {}).get(t, {}).get("qual", 0)))
        for i, t in enumerate(teams):
            grp_col = grp if i == 0 else ""
            cells = (_frozen_cells(grp, t)
                     + _finish_cells(now.get(t))
                     + _finish_cells(now_b.get(t)))
            rows.append(f"{grp_col} & {_abbrev_team(t)} & " + " & ".join(cells) + " \\\\")
        rows.append("\\addlinespace")
    if rows and rows[-1] == "\\addlinespace":
        rows.pop()

    note = ("1st / 2nd / 3rd$^{*}$ / Qual = probability of winning the group, "
            "finishing second, advancing as a best third-placed team, and "
            "qualifying in total. Frozen = pre-kickoff lock ($N$=100{,}000, "
            "never changes); Track~A = result-conditioned, June~10 ratings "
            "($N$=50{,}000); Track~B = result-conditioning + live Elo + "
            "bookmaker odds ($N$=50{,}000). Dashes mark a track not yet "
            "populated for that edition.")

    panel_hdr = ("\\multicolumn{4}{c}{Frozen} & \\multicolumn{4}{c}{Track~A} & "
                 "\\multicolumn{4}{c}{Track~B} \\\\\n"
                 "\\cmidrule(lr){3-6}\\cmidrule(lr){7-10}\\cmidrule(lr){11-14}\n")
    sub_hdr = ("Grp & Team & " + " & ".join(
        ["1st & 2nd & 3rd$^{*}$ & Qual"] * 3) + " \\\\\n\\midrule\n")

    return (
        "\\begin{table}[!t]\\centering\n"
        "\\caption{Group finishing-position probabilities --- Frozen / Track~A "
        "/ Track~B, all teams (live edition M\\liveEditionNum{})}"
        "\\label{tab:live_groupqual_three}\n"
        "{\\setlength{\\tabcolsep}{3pt}\\scriptsize\\begin{threeparttable}\n"
        "\\begin{tabular}{llrrrrrrrrrrrr}\\toprule\n"
        " & & " + panel_hdr
        + sub_hdr
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\n"
        "\\begin{tablenotes}\\notesize\n"
        f"\\item \\textit{{Notes}}: {note}\n"
        "\\end{tablenotes}\\end{threeparttable}}\n\\end{table}"
    )


def fixture_risk_unit(ctx):
    """Table 11: Decisive upcoming fixtures — teams on the qualification bubble
    (10\\% < Track~A advance~\\% < 90\\%) with Frozen and Track~B H/D/A odds."""
    now = ctx.get("now", {})
    expectations = ctx.get("expectations", [])
    results = ctx.get("results", {})
    track_b_map = ctx.get("track_b_map", {})   # {match: {'pick','hda'}} all upcoming fixtures
    group_state = ctx.get("group_state", [])

    played = set(results.get("group", {}).keys())

    rows = []
    for g in group_state:
        grp = g["group"]
        for e in expectations:
            if e.get("group") != grp or str(e["match"]) in played:
                continue
            home, away = e["home"], e["away"]
            h_adv = now.get(home, {}).get("advance_KO", 0)
            a_adv = now.get(away, {}).get("advance_KO", 0)
            bubble = [(t, adv) for t, adv in [(home, h_adv), (away, a_adv)]
                      if 0.10 < adv < 0.90]
            if not bubble:
                continue
            fixture = ic.fixture_tag(f"{home} v {away}")
            bubble_str = "; ".join(f"{ic.code3(t)} {_pct(adv)}\\%" for t, adv in bubble)
            lock_str = "/".join(_ppct(p) for p in e["probs_HDA"])
            hda = track_b_map.get(e["match"], {}).get("hda")
            b_hda = "/".join(_ppct(p) for p in hda) if hda else "--"
            rows.append(
                f"  {grp} & {fixture} & {bubble_str} & {lock_str} & {b_hda} \\\\"
            )

    if not rows:
        return ("\\textit{No upcoming group fixtures with bubble teams; all "
                "qualification spots are effectively decided at this stage.}")

    return (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Decisive upcoming fixtures --- bubble teams and outcome odds "
        "(live edition M\\liveEditionNum{})}\\label{tab:live_fixture_risk}\n"
        "\\begin{footnotesize}\\begin{tabular}{lp{0.28\\textwidth}p{0.22\\textwidth}cc}\\toprule\n"
        "Grp & Fixture & Bubble team(s) (Track~A Qual\\%) & "
        "Frozen H/D/A (\\%) & Track~B H/D/A (\\%) \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular}\\end{footnotesize}\\end{table}"
    )


# Pre-registered decisive fixture + primary forecast risk per group, registered
# before kickoff. These never change; the live risk tracker
# (Table~\ref{tab:live_risk_tracker}) scores their status against the results.
_PREREG_RISK = {
    "A": ("South Korea v Czechia, MD1", "Czechia (68\\% qual.) takes second ahead of South Korea"),
    "B": ("Switzerland v Canada, MD3", "Host Canada (88\\%) wins the group outright"),
    "C": ("Scotland v Morocco, MD2", "Scotland (69\\%) overtakes Morocco for second"),
    "D": ("Turkey v United States, MD3", "Turkey tops the group and reroutes the bracket"),
    "E": ("Ecuador v Germany, MD3", "Ecuador (88\\%, Elo 1935) wins the group, not second"),
    "F": ("Netherlands v Japan, MD1", "Japan (76\\%) wins the group ahead of the Netherlands"),
    "G": ("Egypt v Iran, MD3", "Iran (63\\%) edges Egypt for second"),
    "H": ("Cape Verde v Saudi Arabia (3rd-place race)", "Neither third-placer qualifies; Uruguay slips to second"),
    "I": ("Norway v Senegal, MD2", "Senegal (82\\%) beats Norway and takes second"),
    "J": ("Algeria v Austria, MD3", "Algeria (57\\%) overtakes Austria for second"),
    "K": ("Colombia v Portugal, MD3", "The Elo tie holds and Colombia (94\\%) tops the group"),
    "L": ("England v Croatia, MD1", "Croatia (96\\%) wins the group instead of England"),
}


def _frozen_top2(grp, frozen_finish):
    """The submitted group winner and runner-up: argmax p1, then argmax p2."""
    teams = frozen_finish.get(grp, {})
    if not teams:
        return []
    first = max(teams, key=lambda t: teams[t].get("p1", 0))
    rest = [t for t in teams if t != first]
    if not rest:
        return [first]
    second = max(rest, key=lambda t: teams[t].get("p2", 0))
    return [first, second]


def _current_top2(g, now):
    """Current top two: actual standings when the group is complete, else the
    Track~A advance-probability ranking."""
    if g["played"] >= g["total"]:
        return [r["team"] for r in g["rows"][:2]]
    teams = [r["team"] for r in g["rows"]]
    return sorted(teams, key=lambda t: -now.get(t, {}).get("advance_KO", 0))[:2]


def risk_tracker_unit(ctx):
    """Table 11: live status of each group's pre-registered forecast risk.
    Status is scored programmatically from the submitted top two (Frozen) vs the
    current top two (actual standings if the group is complete, else Track~A)."""
    frozen_finish = ctx.get("frozen_finish", {})
    now = ctx.get("now", {})
    group_state = {g["group"]: g for g in ctx.get("group_state", [])}

    if not frozen_finish:
        return (r"\textit{Risk tracker unavailable; frozen finishing-position "
                r"baseline not loaded for this edition.}")

    played_group = ctx.get("results", {}).get("group", {})
    expectations = ctx.get("expectations", [])

    def _decisive_result(raw_fixture, grp):
        """Result of a pre-registered decisive fixture if it has been played,
        oriented to the fixture's stated home/away order; else None."""
        core = raw_fixture.split(",")[0]
        if " v " not in core:
            return None
        h, a = (t.strip() for t in core.split(" v ", 1))
        for e in expectations:
            if e.get("group") == grp and {e.get("home"), e.get("away")} == {h, a}:
                res = played_group.get(str(e.get("match")))
                if not res:
                    return None
                return res if e.get("home") == h else [res[1], res[0]]
        return None

    rows = []
    for grp in "ABCDEFGHIJKL":
        raw_fixture, risk = _PREREG_RISK[grp]
        fixture = ic.fixture_tag(raw_fixture)   # ISO3 (keeps the ", MDx" suffix)
        g = group_state.get(grp)
        sub = _frozen_top2(grp, frozen_finish)
        if g is None or not sub:
            status, emerging = "$\\triangle$ Pending", "--"
        else:
            cur = _current_top2(g, now)
            held = set(cur) == set(sub)
            complete = g["played"] >= g["total"]
            dres = _decisive_result(raw_fixture, grp)
            if complete and held:
                status = "\\checkmark\\ Resolved"
            elif complete and not held:
                status = "$\\times$ Reversed"
            elif dres is not None:
                # decisive fixture played but group not yet complete: show the
                # score with a provisional verdict from the current top two
                status = (f"Played {dres[0]}--{dres[1]}, "
                          f"{'holding' if held else 'reversing'}")
            elif held:
                status = "$\\triangle$ Pending"
            else:
                status = "$\\triangle$ At risk"
            if not held:
                gained = [t for t in cur if t not in sub]
                dropped = [t for t in sub if t not in cur]
                if gained and dropped:
                    emerging = (f"Track~A now has {_abbrev_team(gained[0])} in the "
                                f"top two over {_abbrev_team(dropped[0])}")
                else:
                    emerging = "Track~A order differs from the submitted top two"
            else:
                emerging = "--"
        rows.append(f"  {grp} & {fixture} & {risk} & {status} & {emerging} \\\\")

    return (
        "\\begin{table}[!h]\\centering\n"
        "\\caption{Pre-registered group risks: live status against the results "
        "so far (live edition M\\liveEditionNum{})}\\label{tab:live_risk_tracker}\n"
        "\\begin{footnotesize}\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}"
        "lp{2.9cm}p{3.9cm}p{2.5cm}p{2.7cm}}\\toprule\n"
        "Grp & Decisive fixture & Pre-registered risk & Status & Emerging issue \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\\end{tabular*}\\end{footnotesize}\n"
        "\\begin{footnotesize}\\textit{Notes}: Status compares the submitted top "
        "two (Frozen modal 1st/2nd) with the current top two --- actual standings "
        "once a group is complete, otherwise the Track~A advance ranking. "
        "\\checkmark\\ Resolved = held at completion; $\\times$ Reversed = a "
        "submitted qualifier displaced; \\emph{Played h--a} = the decisive fixture "
        "is in, with a provisional verdict from the current top two; "
        "$\\triangle$ = group still open.\\end{footnotesize}"
        "\n\\end{table}"
    )
